language: go
sudo: false
go:
  - 1.9.x
  - 1.10.x
  - master
go_import_path: github.com/grpc-ecosystem/grpc-gateway
cache:
  directories:
    - $HOME/local
    - ${TRAVIS_BUILD_DIR}/examples/browser/node_modules
    - $HOME/.cache/_grpc_gateway_bazel
before_install:
  - if [ "${USE_BAZEL}" = true ]; then ./.travis/install-bazel.sh 0.12.0; fi
  - if [ -z "${USE_BAZEL}" ]; then ./.travis/install-protoc.sh 3.1.0; fi
  - if [ -z "${USE_BAZEL}" ]; then ./.travis/install-swagger-codegen.sh 2.2.2; fi
  - if [ -z "${USE_BAZEL}" ]; then nvm install v6.1 && nvm use v6.1 && node --version; fi
  - go get github.com/golang/lint/golint
  - go get github.com/dghubble/sling
  - go get github.com/go-resty/resty
install:
  - go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get github.com/grpc-ecosystem/grpc-gateway/runtime
  - go get github.com/grpc-ecosystem/grpc-gateway/examples
  - go get github.com/grpc-ecosystem/grpc-gateway/examples/server
before_script:
  - sh -c 'cd examples/browser && npm install'
script:
  - if [ "${USE_BAZEL}" = true ]; then ./.travis/bazel-build.sh; fi
  - if [ "${USE_BAZEL}" = true ]; then ./.travis/bazel-test.sh; fi
  - if [ -z "${USE_BAZEL}" ]; then make realclean && make examples SWAGGER_CODEGEN="java -jar $HOME/local/swagger-codegen-cli.jar"; fi
  - if [ -z "${USE_BAZEL}" ] && (go version | grep -q "${GO_VERSION_TO_DIFF_TEST}") && [ -z "${GATEWAY_PLUGIN_FLAGS}" ]; then test -z "$(git status --porcelain)" || (git status; git diff; exit 1); fi
  - if [ -z "${USE_BAZEL}" ]; then env GLOG_logtostderr=1 go test -race -v github.com/grpc-ecosystem/grpc-gateway/...; fi
  - if [ -z "${USE_BAZEL}" ]; then make lint; fi
  - if [ -z "${USE_BAZEL}" ]; then sh -c 'cd examples/browser && node ./node_modules/gulp/bin/gulp'; fi
  - if (go version | grep -q "${GO_VERSION_TO_DIFF_TEST}") && [ -z "${GATEWAY_PLUGIN_FLAGS}" ]; then env GLOG_logtostderr=1 ./bin/coverage; fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - "PATH=$PATH:$HOME/local/bin"
    - GO_VERSION_TO_DIFF_TEST="go version go1\.10\.[0-9]\+ linux/amd64"
  matrix:
    - GATEWAY_PLUGIN_FLAGS=
    - GATEWAY_PLUGIN_FLAGS=request_context=false
matrix:
  include:
    - go: master
      env: USE_BAZEL=true
