// Code generated by go-swagger; DO NOT EDIT.

package echo_rpc

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewABitOfEverythingServiceEchoParams creates a new ABitOfEverythingServiceEchoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewABitOfEverythingServiceEchoParams() *ABitOfEverythingServiceEchoParams {
	return &ABitOfEverythingServiceEchoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewABitOfEverythingServiceEchoParamsWithTimeout creates a new ABitOfEverythingServiceEchoParams object
// with the ability to set a timeout on a request.
func NewABitOfEverythingServiceEchoParamsWithTimeout(timeout time.Duration) *ABitOfEverythingServiceEchoParams {
	return &ABitOfEverythingServiceEchoParams{
		timeout: timeout,
	}
}

// NewABitOfEverythingServiceEchoParamsWithContext creates a new ABitOfEverythingServiceEchoParams object
// with the ability to set a context for a request.
func NewABitOfEverythingServiceEchoParamsWithContext(ctx context.Context) *ABitOfEverythingServiceEchoParams {
	return &ABitOfEverythingServiceEchoParams{
		Context: ctx,
	}
}

// NewABitOfEverythingServiceEchoParamsWithHTTPClient creates a new ABitOfEverythingServiceEchoParams object
// with the ability to set a custom HTTPClient for a request.
func NewABitOfEverythingServiceEchoParamsWithHTTPClient(client *http.Client) *ABitOfEverythingServiceEchoParams {
	return &ABitOfEverythingServiceEchoParams{
		HTTPClient: client,
	}
}

/*
ABitOfEverythingServiceEchoParams contains all the parameters to send to the API endpoint

	for the a bit of everything service echo operation.

	Typically these are written to a http.Request.
*/
type ABitOfEverythingServiceEchoParams struct {

	// Value.
	Value string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the a bit of everything service echo params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ABitOfEverythingServiceEchoParams) WithDefaults() *ABitOfEverythingServiceEchoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the a bit of everything service echo params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ABitOfEverythingServiceEchoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the a bit of everything service echo params
func (o *ABitOfEverythingServiceEchoParams) WithTimeout(timeout time.Duration) *ABitOfEverythingServiceEchoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the a bit of everything service echo params
func (o *ABitOfEverythingServiceEchoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the a bit of everything service echo params
func (o *ABitOfEverythingServiceEchoParams) WithContext(ctx context.Context) *ABitOfEverythingServiceEchoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the a bit of everything service echo params
func (o *ABitOfEverythingServiceEchoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the a bit of everything service echo params
func (o *ABitOfEverythingServiceEchoParams) WithHTTPClient(client *http.Client) *ABitOfEverythingServiceEchoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the a bit of everything service echo params
func (o *ABitOfEverythingServiceEchoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithValue adds the value to the a bit of everything service echo params
func (o *ABitOfEverythingServiceEchoParams) WithValue(value string) *ABitOfEverythingServiceEchoParams {
	o.SetValue(value)
	return o
}

// SetValue adds the value to the a bit of everything service echo params
func (o *ABitOfEverythingServiceEchoParams) SetValue(value string) {
	o.Value = value
}

// WriteToRequest writes these params to a swagger request
func (o *ABitOfEverythingServiceEchoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param value
	if err := r.SetPathParam("value", o.Value); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
