// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/examplepb/a_bit_of_everything.proto

package examplepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import google_protobuf2 "github.com/golang/protobuf/ptypes/duration"
import grpc_gateway_examples_sub "github.com/grpc-ecosystem/grpc-gateway/examples/sub"
import sub2 "github.com/grpc-ecosystem/grpc-gateway/examples/sub2"
import google_protobuf3 "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// NumericEnum is one or zero.
type NumericEnum int32

const (
	// ZERO means 0
	NumericEnum_ZERO NumericEnum = 0
	// ONE means 1
	NumericEnum_ONE NumericEnum = 1
)

var NumericEnum_name = map[int32]string{
	0: "ZERO",
	1: "ONE",
}
var NumericEnum_value = map[string]int32{
	"ZERO": 0,
	"ONE":  1,
}

func (x NumericEnum) String() string {
	return proto.EnumName(NumericEnum_name, int32(x))
}
func (NumericEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// DeepEnum is one or zero.
type ABitOfEverything_Nested_DeepEnum int32

const (
	// FALSE is false.
	ABitOfEverything_Nested_FALSE ABitOfEverything_Nested_DeepEnum = 0
	// TRUE is true.
	ABitOfEverything_Nested_TRUE ABitOfEverything_Nested_DeepEnum = 1
)

var ABitOfEverything_Nested_DeepEnum_name = map[int32]string{
	0: "FALSE",
	1: "TRUE",
}
var ABitOfEverything_Nested_DeepEnum_value = map[string]int32{
	"FALSE": 0,
	"TRUE":  1,
}

func (x ABitOfEverything_Nested_DeepEnum) String() string {
	return proto.EnumName(ABitOfEverything_Nested_DeepEnum_name, int32(x))
}
func (ABitOfEverything_Nested_DeepEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{0, 0, 0}
}

// Intentionaly complicated message type to cover much features of Protobuf.
// NEXT ID: 30
type ABitOfEverything struct {
	SingleNested        *ABitOfEverything_Nested   `protobuf:"bytes,25,opt,name=single_nested,json=singleNested" json:"single_nested,omitempty"`
	Uuid                string                     `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Nested              []*ABitOfEverything_Nested `protobuf:"bytes,2,rep,name=nested" json:"nested,omitempty"`
	FloatValue          float32                    `protobuf:"fixed32,3,opt,name=float_value,json=floatValue" json:"float_value,omitempty"`
	DoubleValue         float64                    `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue" json:"double_value,omitempty"`
	Int64Value          int64                      `protobuf:"varint,5,opt,name=int64_value,json=int64Value" json:"int64_value,omitempty"`
	Uint64Value         uint64                     `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value" json:"uint64_value,omitempty"`
	Int32Value          int32                      `protobuf:"varint,7,opt,name=int32_value,json=int32Value" json:"int32_value,omitempty"`
	Fixed64Value        uint64                     `protobuf:"fixed64,8,opt,name=fixed64_value,json=fixed64Value" json:"fixed64_value,omitempty"`
	Fixed32Value        uint32                     `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value" json:"fixed32_value,omitempty"`
	BoolValue           bool                       `protobuf:"varint,10,opt,name=bool_value,json=boolValue" json:"bool_value,omitempty"`
	StringValue         string                     `protobuf:"bytes,11,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	BytesValue          []byte                     `protobuf:"bytes,29,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	Uint32Value         uint32                     `protobuf:"varint,13,opt,name=uint32_value,json=uint32Value" json:"uint32_value,omitempty"`
	EnumValue           NumericEnum                `protobuf:"varint,14,opt,name=enum_value,json=enumValue,enum=grpc.gateway.examples.examplepb.NumericEnum" json:"enum_value,omitempty"`
	Sfixed32Value       int32                      `protobuf:"fixed32,15,opt,name=sfixed32_value,json=sfixed32Value" json:"sfixed32_value,omitempty"`
	Sfixed64Value       int64                      `protobuf:"fixed64,16,opt,name=sfixed64_value,json=sfixed64Value" json:"sfixed64_value,omitempty"`
	Sint32Value         int32                      `protobuf:"zigzag32,17,opt,name=sint32_value,json=sint32Value" json:"sint32_value,omitempty"`
	Sint64Value         int64                      `protobuf:"zigzag64,18,opt,name=sint64_value,json=sint64Value" json:"sint64_value,omitempty"`
	RepeatedStringValue []string                   `protobuf:"bytes,19,rep,name=repeated_string_value,json=repeatedStringValue" json:"repeated_string_value,omitempty"`
	// Types that are valid to be assigned to OneofValue:
	//	*ABitOfEverything_OneofEmpty
	//	*ABitOfEverything_OneofString
	OneofValue               isABitOfEverything_OneofValue       `protobuf_oneof:"oneof_value"`
	MapValue                 map[string]NumericEnum              `protobuf:"bytes,22,rep,name=map_value,json=mapValue" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=grpc.gateway.examples.examplepb.NumericEnum"`
	MappedStringValue        map[string]string                   `protobuf:"bytes,23,rep,name=mapped_string_value,json=mappedStringValue" json:"mapped_string_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MappedNestedValue        map[string]*ABitOfEverything_Nested `protobuf:"bytes,24,rep,name=mapped_nested_value,json=mappedNestedValue" json:"mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NonConventionalNameValue string                              `protobuf:"bytes,26,opt,name=nonConventionalNameValue" json:"nonConventionalNameValue,omitempty"`
	TimestampValue           *google_protobuf3.Timestamp         `protobuf:"bytes,27,opt,name=timestamp_value,json=timestampValue" json:"timestamp_value,omitempty"`
	// repeated enum value. it is comma-separated in query
	RepeatedEnumValue []NumericEnum `protobuf:"varint,28,rep,packed,name=repeated_enum_value,json=repeatedEnumValue,enum=grpc.gateway.examples.examplepb.NumericEnum" json:"repeated_enum_value,omitempty"`
}

func (m *ABitOfEverything) Reset()                    { *m = ABitOfEverything{} }
func (m *ABitOfEverything) String() string            { return proto.CompactTextString(m) }
func (*ABitOfEverything) ProtoMessage()               {}
func (*ABitOfEverything) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type isABitOfEverything_OneofValue interface {
	isABitOfEverything_OneofValue()
}

type ABitOfEverything_OneofEmpty struct {
	OneofEmpty *google_protobuf1.Empty `protobuf:"bytes,20,opt,name=oneof_empty,json=oneofEmpty,oneof"`
}
type ABitOfEverything_OneofString struct {
	OneofString string `protobuf:"bytes,21,opt,name=oneof_string,json=oneofString,oneof"`
}

func (*ABitOfEverything_OneofEmpty) isABitOfEverything_OneofValue()  {}
func (*ABitOfEverything_OneofString) isABitOfEverything_OneofValue() {}

func (m *ABitOfEverything) GetOneofValue() isABitOfEverything_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *ABitOfEverything) GetSingleNested() *ABitOfEverything_Nested {
	if m != nil {
		return m.SingleNested
	}
	return nil
}

func (m *ABitOfEverything) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ABitOfEverything) GetNested() []*ABitOfEverything_Nested {
	if m != nil {
		return m.Nested
	}
	return nil
}

func (m *ABitOfEverything) GetFloatValue() float32 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *ABitOfEverything) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *ABitOfEverything) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *ABitOfEverything) GetUint64Value() uint64 {
	if m != nil {
		return m.Uint64Value
	}
	return 0
}

func (m *ABitOfEverything) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *ABitOfEverything) GetFixed64Value() uint64 {
	if m != nil {
		return m.Fixed64Value
	}
	return 0
}

func (m *ABitOfEverything) GetFixed32Value() uint32 {
	if m != nil {
		return m.Fixed32Value
	}
	return 0
}

func (m *ABitOfEverything) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *ABitOfEverything) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *ABitOfEverything) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *ABitOfEverything) GetUint32Value() uint32 {
	if m != nil {
		return m.Uint32Value
	}
	return 0
}

func (m *ABitOfEverything) GetEnumValue() NumericEnum {
	if m != nil {
		return m.EnumValue
	}
	return NumericEnum_ZERO
}

func (m *ABitOfEverything) GetSfixed32Value() int32 {
	if m != nil {
		return m.Sfixed32Value
	}
	return 0
}

func (m *ABitOfEverything) GetSfixed64Value() int64 {
	if m != nil {
		return m.Sfixed64Value
	}
	return 0
}

func (m *ABitOfEverything) GetSint32Value() int32 {
	if m != nil {
		return m.Sint32Value
	}
	return 0
}

func (m *ABitOfEverything) GetSint64Value() int64 {
	if m != nil {
		return m.Sint64Value
	}
	return 0
}

func (m *ABitOfEverything) GetRepeatedStringValue() []string {
	if m != nil {
		return m.RepeatedStringValue
	}
	return nil
}

func (m *ABitOfEverything) GetOneofEmpty() *google_protobuf1.Empty {
	if x, ok := m.GetOneofValue().(*ABitOfEverything_OneofEmpty); ok {
		return x.OneofEmpty
	}
	return nil
}

func (m *ABitOfEverything) GetOneofString() string {
	if x, ok := m.GetOneofValue().(*ABitOfEverything_OneofString); ok {
		return x.OneofString
	}
	return ""
}

func (m *ABitOfEverything) GetMapValue() map[string]NumericEnum {
	if m != nil {
		return m.MapValue
	}
	return nil
}

func (m *ABitOfEverything) GetMappedStringValue() map[string]string {
	if m != nil {
		return m.MappedStringValue
	}
	return nil
}

func (m *ABitOfEverything) GetMappedNestedValue() map[string]*ABitOfEverything_Nested {
	if m != nil {
		return m.MappedNestedValue
	}
	return nil
}

func (m *ABitOfEverything) GetNonConventionalNameValue() string {
	if m != nil {
		return m.NonConventionalNameValue
	}
	return ""
}

func (m *ABitOfEverything) GetTimestampValue() *google_protobuf3.Timestamp {
	if m != nil {
		return m.TimestampValue
	}
	return nil
}

func (m *ABitOfEverything) GetRepeatedEnumValue() []NumericEnum {
	if m != nil {
		return m.RepeatedEnumValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ABitOfEverything) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ABitOfEverything_OneofMarshaler, _ABitOfEverything_OneofUnmarshaler, _ABitOfEverything_OneofSizer, []interface{}{
		(*ABitOfEverything_OneofEmpty)(nil),
		(*ABitOfEverything_OneofString)(nil),
	}
}

func _ABitOfEverything_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ABitOfEverything)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *ABitOfEverything_OneofEmpty:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OneofEmpty); err != nil {
			return err
		}
	case *ABitOfEverything_OneofString:
		b.EncodeVarint(21<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.OneofString)
	case nil:
	default:
		return fmt.Errorf("ABitOfEverything.OneofValue has unexpected type %T", x)
	}
	return nil
}

func _ABitOfEverything_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ABitOfEverything)
	switch tag {
	case 20: // oneof_value.oneof_empty
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.Empty)
		err := b.DecodeMessage(msg)
		m.OneofValue = &ABitOfEverything_OneofEmpty{msg}
		return true, err
	case 21: // oneof_value.oneof_string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofValue = &ABitOfEverything_OneofString{x}
		return true, err
	default:
		return false, nil
	}
}

func _ABitOfEverything_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ABitOfEverything)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *ABitOfEverything_OneofEmpty:
		s := proto.Size(x.OneofEmpty)
		n += proto.SizeVarint(20<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ABitOfEverything_OneofString:
		n += proto.SizeVarint(21<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.OneofString)))
		n += len(x.OneofString)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Nested is nested type.
type ABitOfEverything_Nested struct {
	// name is nested field.
	Name   string                           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Amount uint32                           `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Ok     ABitOfEverything_Nested_DeepEnum `protobuf:"varint,3,opt,name=ok,enum=grpc.gateway.examples.examplepb.ABitOfEverything_Nested_DeepEnum" json:"ok,omitempty"`
}

func (m *ABitOfEverything_Nested) Reset()                    { *m = ABitOfEverything_Nested{} }
func (m *ABitOfEverything_Nested) String() string            { return proto.CompactTextString(m) }
func (*ABitOfEverything_Nested) ProtoMessage()               {}
func (*ABitOfEverything_Nested) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

func (m *ABitOfEverything_Nested) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ABitOfEverything_Nested) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ABitOfEverything_Nested) GetOk() ABitOfEverything_Nested_DeepEnum {
	if m != nil {
		return m.Ok
	}
	return ABitOfEverything_Nested_FALSE
}

type ABitOfEverythingSansEnum struct {
	SingleNested        *ABitOfEverythingSansEnum_Nested   `protobuf:"bytes,25,opt,name=single_nested,json=singleNested" json:"single_nested,omitempty"`
	Uuid                string                             `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Nested              []*ABitOfEverythingSansEnum_Nested `protobuf:"bytes,2,rep,name=nested" json:"nested,omitempty"`
	FloatValue          float32                            `protobuf:"fixed32,3,opt,name=float_value,json=floatValue" json:"float_value,omitempty"`
	DoubleValue         float64                            `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue" json:"double_value,omitempty"`
	Int64Value          int64                              `protobuf:"varint,5,opt,name=int64_value,json=int64Value" json:"int64_value,omitempty"`
	Uint64Value         uint64                             `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value" json:"uint64_value,omitempty"`
	Int32Value          int32                              `protobuf:"varint,7,opt,name=int32_value,json=int32Value" json:"int32_value,omitempty"`
	Fixed64Value        uint64                             `protobuf:"fixed64,8,opt,name=fixed64_value,json=fixed64Value" json:"fixed64_value,omitempty"`
	Fixed32Value        uint32                             `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value" json:"fixed32_value,omitempty"`
	BoolValue           bool                               `protobuf:"varint,10,opt,name=bool_value,json=boolValue" json:"bool_value,omitempty"`
	StringValue         string                             `protobuf:"bytes,11,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	BytesValue          []byte                             `protobuf:"bytes,29,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	Uint32Value         uint32                             `protobuf:"varint,13,opt,name=uint32_value,json=uint32Value" json:"uint32_value,omitempty"`
	Sfixed32Value       int32                              `protobuf:"fixed32,15,opt,name=sfixed32_value,json=sfixed32Value" json:"sfixed32_value,omitempty"`
	Sfixed64Value       int64                              `protobuf:"fixed64,16,opt,name=sfixed64_value,json=sfixed64Value" json:"sfixed64_value,omitempty"`
	Sint32Value         int32                              `protobuf:"zigzag32,17,opt,name=sint32_value,json=sint32Value" json:"sint32_value,omitempty"`
	Sint64Value         int64                              `protobuf:"zigzag64,18,opt,name=sint64_value,json=sint64Value" json:"sint64_value,omitempty"`
	RepeatedStringValue []string                           `protobuf:"bytes,19,rep,name=repeated_string_value,json=repeatedStringValue" json:"repeated_string_value,omitempty"`
	// Types that are valid to be assigned to OneofValue:
	//	*ABitOfEverythingSansEnum_OneofEmpty
	//	*ABitOfEverythingSansEnum_OneofString
	OneofValue               isABitOfEverythingSansEnum_OneofValue       `protobuf_oneof:"oneof_value"`
	MappedStringValue        map[string]string                           `protobuf:"bytes,23,rep,name=mapped_string_value,json=mappedStringValue" json:"mapped_string_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MappedNestedValue        map[string]*ABitOfEverythingSansEnum_Nested `protobuf:"bytes,24,rep,name=mapped_nested_value,json=mappedNestedValue" json:"mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NonConventionalNameValue string                                      `protobuf:"bytes,26,opt,name=nonConventionalNameValue" json:"nonConventionalNameValue,omitempty"`
	TimestampValue           *google_protobuf3.Timestamp                 `protobuf:"bytes,27,opt,name=timestamp_value,json=timestampValue" json:"timestamp_value,omitempty"`
}

func (m *ABitOfEverythingSansEnum) Reset()                    { *m = ABitOfEverythingSansEnum{} }
func (m *ABitOfEverythingSansEnum) String() string            { return proto.CompactTextString(m) }
func (*ABitOfEverythingSansEnum) ProtoMessage()               {}
func (*ABitOfEverythingSansEnum) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type isABitOfEverythingSansEnum_OneofValue interface {
	isABitOfEverythingSansEnum_OneofValue()
}

type ABitOfEverythingSansEnum_OneofEmpty struct {
	OneofEmpty *google_protobuf1.Empty `protobuf:"bytes,20,opt,name=oneof_empty,json=oneofEmpty,oneof"`
}
type ABitOfEverythingSansEnum_OneofString struct {
	OneofString string `protobuf:"bytes,21,opt,name=oneof_string,json=oneofString,oneof"`
}

func (*ABitOfEverythingSansEnum_OneofEmpty) isABitOfEverythingSansEnum_OneofValue()  {}
func (*ABitOfEverythingSansEnum_OneofString) isABitOfEverythingSansEnum_OneofValue() {}

func (m *ABitOfEverythingSansEnum) GetOneofValue() isABitOfEverythingSansEnum_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *ABitOfEverythingSansEnum) GetSingleNested() *ABitOfEverythingSansEnum_Nested {
	if m != nil {
		return m.SingleNested
	}
	return nil
}

func (m *ABitOfEverythingSansEnum) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ABitOfEverythingSansEnum) GetNested() []*ABitOfEverythingSansEnum_Nested {
	if m != nil {
		return m.Nested
	}
	return nil
}

func (m *ABitOfEverythingSansEnum) GetFloatValue() float32 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *ABitOfEverythingSansEnum) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *ABitOfEverythingSansEnum) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *ABitOfEverythingSansEnum) GetUint64Value() uint64 {
	if m != nil {
		return m.Uint64Value
	}
	return 0
}

func (m *ABitOfEverythingSansEnum) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *ABitOfEverythingSansEnum) GetFixed64Value() uint64 {
	if m != nil {
		return m.Fixed64Value
	}
	return 0
}

func (m *ABitOfEverythingSansEnum) GetFixed32Value() uint32 {
	if m != nil {
		return m.Fixed32Value
	}
	return 0
}

func (m *ABitOfEverythingSansEnum) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *ABitOfEverythingSansEnum) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *ABitOfEverythingSansEnum) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *ABitOfEverythingSansEnum) GetUint32Value() uint32 {
	if m != nil {
		return m.Uint32Value
	}
	return 0
}

func (m *ABitOfEverythingSansEnum) GetSfixed32Value() int32 {
	if m != nil {
		return m.Sfixed32Value
	}
	return 0
}

func (m *ABitOfEverythingSansEnum) GetSfixed64Value() int64 {
	if m != nil {
		return m.Sfixed64Value
	}
	return 0
}

func (m *ABitOfEverythingSansEnum) GetSint32Value() int32 {
	if m != nil {
		return m.Sint32Value
	}
	return 0
}

func (m *ABitOfEverythingSansEnum) GetSint64Value() int64 {
	if m != nil {
		return m.Sint64Value
	}
	return 0
}

func (m *ABitOfEverythingSansEnum) GetRepeatedStringValue() []string {
	if m != nil {
		return m.RepeatedStringValue
	}
	return nil
}

func (m *ABitOfEverythingSansEnum) GetOneofEmpty() *google_protobuf1.Empty {
	if x, ok := m.GetOneofValue().(*ABitOfEverythingSansEnum_OneofEmpty); ok {
		return x.OneofEmpty
	}
	return nil
}

func (m *ABitOfEverythingSansEnum) GetOneofString() string {
	if x, ok := m.GetOneofValue().(*ABitOfEverythingSansEnum_OneofString); ok {
		return x.OneofString
	}
	return ""
}

func (m *ABitOfEverythingSansEnum) GetMappedStringValue() map[string]string {
	if m != nil {
		return m.MappedStringValue
	}
	return nil
}

func (m *ABitOfEverythingSansEnum) GetMappedNestedValue() map[string]*ABitOfEverythingSansEnum_Nested {
	if m != nil {
		return m.MappedNestedValue
	}
	return nil
}

func (m *ABitOfEverythingSansEnum) GetNonConventionalNameValue() string {
	if m != nil {
		return m.NonConventionalNameValue
	}
	return ""
}

func (m *ABitOfEverythingSansEnum) GetTimestampValue() *google_protobuf3.Timestamp {
	if m != nil {
		return m.TimestampValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ABitOfEverythingSansEnum) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ABitOfEverythingSansEnum_OneofMarshaler, _ABitOfEverythingSansEnum_OneofUnmarshaler, _ABitOfEverythingSansEnum_OneofSizer, []interface{}{
		(*ABitOfEverythingSansEnum_OneofEmpty)(nil),
		(*ABitOfEverythingSansEnum_OneofString)(nil),
	}
}

func _ABitOfEverythingSansEnum_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ABitOfEverythingSansEnum)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *ABitOfEverythingSansEnum_OneofEmpty:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OneofEmpty); err != nil {
			return err
		}
	case *ABitOfEverythingSansEnum_OneofString:
		b.EncodeVarint(21<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.OneofString)
	case nil:
	default:
		return fmt.Errorf("ABitOfEverythingSansEnum.OneofValue has unexpected type %T", x)
	}
	return nil
}

func _ABitOfEverythingSansEnum_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ABitOfEverythingSansEnum)
	switch tag {
	case 20: // oneof_value.oneof_empty
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.Empty)
		err := b.DecodeMessage(msg)
		m.OneofValue = &ABitOfEverythingSansEnum_OneofEmpty{msg}
		return true, err
	case 21: // oneof_value.oneof_string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofValue = &ABitOfEverythingSansEnum_OneofString{x}
		return true, err
	default:
		return false, nil
	}
}

func _ABitOfEverythingSansEnum_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ABitOfEverythingSansEnum)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *ABitOfEverythingSansEnum_OneofEmpty:
		s := proto.Size(x.OneofEmpty)
		n += proto.SizeVarint(20<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ABitOfEverythingSansEnum_OneofString:
		n += proto.SizeVarint(21<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.OneofString)))
		n += len(x.OneofString)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ABitOfEverythingSansEnum_Nested struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Amount uint32 `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *ABitOfEverythingSansEnum_Nested) Reset()         { *m = ABitOfEverythingSansEnum_Nested{} }
func (m *ABitOfEverythingSansEnum_Nested) String() string { return proto.CompactTextString(m) }
func (*ABitOfEverythingSansEnum_Nested) ProtoMessage()    {}
func (*ABitOfEverythingSansEnum_Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{1, 0}
}

func (m *ABitOfEverythingSansEnum_Nested) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ABitOfEverythingSansEnum_Nested) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type Body struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Body) Reset()                    { *m = Body{} }
func (m *Body) String() string            { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()               {}
func (*Body) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Body) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MessageWithBody struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Data *Body  `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *MessageWithBody) Reset()                    { *m = MessageWithBody{} }
func (m *MessageWithBody) String() string            { return proto.CompactTextString(m) }
func (*MessageWithBody) ProtoMessage()               {}
func (*MessageWithBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *MessageWithBody) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageWithBody) GetData() *Body {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ABitOfEverything)(nil), "grpc.gateway.examples.examplepb.ABitOfEverything")
	proto.RegisterType((*ABitOfEverything_Nested)(nil), "grpc.gateway.examples.examplepb.ABitOfEverything.Nested")
	proto.RegisterType((*ABitOfEverythingSansEnum)(nil), "grpc.gateway.examples.examplepb.ABitOfEverythingSansEnum")
	proto.RegisterType((*ABitOfEverythingSansEnum_Nested)(nil), "grpc.gateway.examples.examplepb.ABitOfEverythingSansEnum.Nested")
	proto.RegisterType((*Body)(nil), "grpc.gateway.examples.examplepb.Body")
	proto.RegisterType((*MessageWithBody)(nil), "grpc.gateway.examples.examplepb.MessageWithBody")
	proto.RegisterEnum("grpc.gateway.examples.examplepb.NumericEnum", NumericEnum_name, NumericEnum_value)
	proto.RegisterEnum("grpc.gateway.examples.examplepb.ABitOfEverything_Nested_DeepEnum", ABitOfEverything_Nested_DeepEnum_name, ABitOfEverything_Nested_DeepEnum_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ABitOfEverythingService service

type ABitOfEverythingServiceClient interface {
	Create(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	CreateBody(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	CreateSansEnum(ctx context.Context, in *ABitOfEverythingSansEnum, opts ...grpc.CallOption) (*ABitOfEverythingSansEnum, error)
	CreateBodySansEnum(ctx context.Context, in *ABitOfEverythingSansEnum, opts ...grpc.CallOption) (*ABitOfEverythingSansEnum, error)
	Lookup(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*ABitOfEverything, error)
	Update(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Delete(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	GetQuery(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Echo allows posting a StringMessage value.
	//
	// It also exposes multiple bindings.
	//
	// This makes it useful when validating that the OpenAPI v2 API
	// description exposes documentation correctly on all paths
	// defined as additional_bindings in the proto.
	Echo(ctx context.Context, in *grpc_gateway_examples_sub.StringMessage, opts ...grpc.CallOption) (*grpc_gateway_examples_sub.StringMessage, error)
	DeepPathEcho(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	NoBindings(ctx context.Context, in *google_protobuf2.Duration, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Timeout(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ErrorWithDetails(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	GetMessageWithBody(ctx context.Context, in *MessageWithBody, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	PostWithEmptyBody(ctx context.Context, in *Body, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type aBitOfEverythingServiceClient struct {
	cc *grpc.ClientConn
}

func NewABitOfEverythingServiceClient(cc *grpc.ClientConn) ABitOfEverythingServiceClient {
	return &aBitOfEverythingServiceClient{cc}
}

func (c *aBitOfEverythingServiceClient) Create(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) CreateBody(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/CreateBody", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) CreateSansEnum(ctx context.Context, in *ABitOfEverythingSansEnum, opts ...grpc.CallOption) (*ABitOfEverythingSansEnum, error) {
	out := new(ABitOfEverythingSansEnum)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/CreateSansEnum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) CreateBodySansEnum(ctx context.Context, in *ABitOfEverythingSansEnum, opts ...grpc.CallOption) (*ABitOfEverythingSansEnum, error) {
	out := new(ABitOfEverythingSansEnum)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/CreateBodySansEnum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Lookup(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Lookup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Update(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Delete(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) GetQuery(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetQuery", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Echo(ctx context.Context, in *grpc_gateway_examples_sub.StringMessage, opts ...grpc.CallOption) (*grpc_gateway_examples_sub.StringMessage, error) {
	out := new(grpc_gateway_examples_sub.StringMessage)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) DeepPathEcho(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/DeepPathEcho", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) NoBindings(ctx context.Context, in *google_protobuf2.Duration, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/NoBindings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Timeout(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Timeout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) ErrorWithDetails(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/ErrorWithDetails", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) GetMessageWithBody(ctx context.Context, in *MessageWithBody, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetMessageWithBody", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) PostWithEmptyBody(ctx context.Context, in *Body, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/PostWithEmptyBody", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ABitOfEverythingService service

type ABitOfEverythingServiceServer interface {
	Create(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	CreateBody(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	CreateSansEnum(context.Context, *ABitOfEverythingSansEnum) (*ABitOfEverythingSansEnum, error)
	CreateBodySansEnum(context.Context, *ABitOfEverythingSansEnum) (*ABitOfEverythingSansEnum, error)
	Lookup(context.Context, *sub2.IdMessage) (*ABitOfEverything, error)
	Update(context.Context, *ABitOfEverything) (*google_protobuf1.Empty, error)
	Delete(context.Context, *sub2.IdMessage) (*google_protobuf1.Empty, error)
	GetQuery(context.Context, *ABitOfEverything) (*google_protobuf1.Empty, error)
	// Echo allows posting a StringMessage value.
	//
	// It also exposes multiple bindings.
	//
	// This makes it useful when validating that the OpenAPI v2 API
	// description exposes documentation correctly on all paths
	// defined as additional_bindings in the proto.
	Echo(context.Context, *grpc_gateway_examples_sub.StringMessage) (*grpc_gateway_examples_sub.StringMessage, error)
	DeepPathEcho(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	NoBindings(context.Context, *google_protobuf2.Duration) (*google_protobuf1.Empty, error)
	Timeout(context.Context, *google_protobuf1.Empty) (*google_protobuf1.Empty, error)
	ErrorWithDetails(context.Context, *google_protobuf1.Empty) (*google_protobuf1.Empty, error)
	GetMessageWithBody(context.Context, *MessageWithBody) (*google_protobuf1.Empty, error)
	PostWithEmptyBody(context.Context, *Body) (*google_protobuf1.Empty, error)
}

func RegisterABitOfEverythingServiceServer(s *grpc.Server, srv ABitOfEverythingServiceServer) {
	s.RegisterService(&_ABitOfEverythingService_serviceDesc, srv)
}

func _ABitOfEverythingService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Create(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_CreateBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).CreateBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/CreateBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).CreateBody(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_CreateSansEnum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverythingSansEnum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).CreateSansEnum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/CreateSansEnum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).CreateSansEnum(ctx, req.(*ABitOfEverythingSansEnum))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_CreateBodySansEnum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverythingSansEnum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).CreateBodySansEnum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/CreateBodySansEnum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).CreateBodySansEnum(ctx, req.(*ABitOfEverythingSansEnum))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sub2.IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Lookup(ctx, req.(*sub2.IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Update(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sub2.IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Delete(ctx, req.(*sub2.IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_GetQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).GetQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).GetQuery(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(grpc_gateway_examples_sub.StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Echo(ctx, req.(*grpc_gateway_examples_sub.StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_DeepPathEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).DeepPathEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/DeepPathEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).DeepPathEcho(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_NoBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf2.Duration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).NoBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/NoBindings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).NoBindings(ctx, req.(*google_protobuf2.Duration))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Timeout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Timeout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Timeout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Timeout(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_ErrorWithDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).ErrorWithDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/ErrorWithDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).ErrorWithDetails(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_GetMessageWithBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageWithBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).GetMessageWithBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetMessageWithBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).GetMessageWithBody(ctx, req.(*MessageWithBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_PostWithEmptyBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Body)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).PostWithEmptyBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/PostWithEmptyBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).PostWithEmptyBody(ctx, req.(*Body))
	}
	return interceptor(ctx, in, info, handler)
}

var _ABitOfEverythingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.examplepb.ABitOfEverythingService",
	HandlerType: (*ABitOfEverythingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ABitOfEverythingService_Create_Handler,
		},
		{
			MethodName: "CreateBody",
			Handler:    _ABitOfEverythingService_CreateBody_Handler,
		},
		{
			MethodName: "CreateSansEnum",
			Handler:    _ABitOfEverythingService_CreateSansEnum_Handler,
		},
		{
			MethodName: "CreateBodySansEnum",
			Handler:    _ABitOfEverythingService_CreateBodySansEnum_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _ABitOfEverythingService_Lookup_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ABitOfEverythingService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ABitOfEverythingService_Delete_Handler,
		},
		{
			MethodName: "GetQuery",
			Handler:    _ABitOfEverythingService_GetQuery_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _ABitOfEverythingService_Echo_Handler,
		},
		{
			MethodName: "DeepPathEcho",
			Handler:    _ABitOfEverythingService_DeepPathEcho_Handler,
		},
		{
			MethodName: "NoBindings",
			Handler:    _ABitOfEverythingService_NoBindings_Handler,
		},
		{
			MethodName: "Timeout",
			Handler:    _ABitOfEverythingService_Timeout_Handler,
		},
		{
			MethodName: "ErrorWithDetails",
			Handler:    _ABitOfEverythingService_ErrorWithDetails_Handler,
		},
		{
			MethodName: "GetMessageWithBody",
			Handler:    _ABitOfEverythingService_GetMessageWithBody_Handler,
		},
		{
			MethodName: "PostWithEmptyBody",
			Handler:    _ABitOfEverythingService_PostWithEmptyBody_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/examplepb/a_bit_of_everything.proto",
}

// Client API for AnotherServiceWithNoBindings service

type AnotherServiceWithNoBindingsClient interface {
	NoBindings(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type anotherServiceWithNoBindingsClient struct {
	cc *grpc.ClientConn
}

func NewAnotherServiceWithNoBindingsClient(cc *grpc.ClientConn) AnotherServiceWithNoBindingsClient {
	return &anotherServiceWithNoBindingsClient{cc}
}

func (c *anotherServiceWithNoBindingsClient) NoBindings(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/grpc.gateway.examples.examplepb.AnotherServiceWithNoBindings/NoBindings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AnotherServiceWithNoBindings service

type AnotherServiceWithNoBindingsServer interface {
	NoBindings(context.Context, *google_protobuf1.Empty) (*google_protobuf1.Empty, error)
}

func RegisterAnotherServiceWithNoBindingsServer(s *grpc.Server, srv AnotherServiceWithNoBindingsServer) {
	s.RegisterService(&_AnotherServiceWithNoBindings_serviceDesc, srv)
}

func _AnotherServiceWithNoBindings_NoBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnotherServiceWithNoBindingsServer).NoBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.AnotherServiceWithNoBindings/NoBindings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnotherServiceWithNoBindingsServer).NoBindings(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnotherServiceWithNoBindings_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.examplepb.AnotherServiceWithNoBindings",
	HandlerType: (*AnotherServiceWithNoBindingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NoBindings",
			Handler:    _AnotherServiceWithNoBindings_NoBindings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/examplepb/a_bit_of_everything.proto",
}

func init() { proto.RegisterFile("examples/examplepb/a_bit_of_everything.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1949 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0xdb, 0x6f, 0xdb, 0xd6,
	0x19, 0xf7, 0x91, 0x1c, 0xc5, 0xfe, 0xe4, 0x8b, 0x7c, 0x9c, 0x38, 0x8a, 0xe2, 0xd6, 0x27, 0x6c,
	0xba, 0xb1, 0x5e, 0x4c, 0x36, 0x4a, 0x30, 0x34, 0x06, 0xb6, 0x56, 0x8e, 0xd5, 0xa4, 0x58, 0xe3,
	0x38, 0x4c, 0x9b, 0x05, 0x59, 0x3a, 0x83, 0x12, 0x8f, 0x25, 0x36, 0x22, 0x0f, 0xc7, 0x73, 0xe8,
	0x58, 0xf0, 0x3c, 0x0c, 0x2b, 0xd0, 0x6d, 0xaf, 0xde, 0xdb, 0x1e, 0xfa, 0x32, 0x60, 0xd8, 0x30,
	0x14, 0xd8, 0xcb, 0xb0, 0x87, 0x01, 0x5b, 0xdf, 0xf6, 0x07, 0xec, 0x2f, 0x18, 0xb0, 0xa7, 0xfd,
	0x15, 0x03, 0x0f, 0x2f, 0xa6, 0x64, 0x6b, 0xb2, 0xec, 0xa2, 0x45, 0x81, 0x3c, 0x99, 0x3c, 0xe7,
	0xbb, 0xfc, 0xbe, 0xfb, 0x47, 0x19, 0xae, 0xd3, 0x5d, 0xd3, 0xf1, 0x3a, 0x94, 0xeb, 0xf1, 0x83,
	0xd7, 0xd0, 0xcd, 0xad, 0x86, 0x2d, 0xb6, 0xd8, 0xf6, 0x16, 0xdd, 0xa1, 0x7e, 0x57, 0xb4, 0x6d,
	0xb7, 0xa5, 0x79, 0x3e, 0x13, 0x0c, 0x2f, 0xb5, 0x7c, 0xaf, 0xa9, 0xb5, 0x4c, 0x41, 0x5f, 0x98,
	0x5d, 0x2d, 0x61, 0xd5, 0x52, 0xd6, 0xca, 0x62, 0x8b, 0xb1, 0x56, 0x87, 0xea, 0xa6, 0x67, 0xeb,
	0xa6, 0xeb, 0x32, 0x61, 0x0a, 0x9b, 0xb9, 0x3c, 0x62, 0xaf, 0x5c, 0x89, 0x6f, 0xe5, 0x5b, 0x23,
	0xd8, 0xd6, 0xa9, 0xe3, 0x89, 0x6e, 0x7c, 0xf9, 0x6a, 0xff, 0xa5, 0x15, 0xf8, 0x92, 0x3b, 0xbe,
	0xaf, 0xa4, 0x48, 0x79, 0xd0, 0xd0, 0x1d, 0xca, 0xb9, 0xd9, 0xa2, 0x89, 0xe0, 0xec, 0x5d, 0xb5,
	0xef, 0x72, 0xa9, 0x5f, 0xb0, 0xb0, 0x1d, 0xca, 0x85, 0xe9, 0x78, 0x31, 0xc1, 0x75, 0xf9, 0xa7,
	0xb9, 0xd2, 0xa2, 0xee, 0x0a, 0x7f, 0x61, 0xb6, 0x5a, 0xd4, 0xd7, 0x99, 0x27, 0x81, 0x1f, 0x35,
	0x42, 0xf9, 0x7b, 0x09, 0x4a, 0xb5, 0x35, 0x5b, 0x3c, 0xd8, 0xae, 0xa7, 0xee, 0xc1, 0x1f, 0xc1,
	0x34, 0xb7, 0xdd, 0x56, 0x87, 0x6e, 0xb9, 0x94, 0x0b, 0x6a, 0x95, 0x2f, 0x13, 0xa4, 0x16, 0xab,
	0x6f, 0x69, 0x43, 0x1c, 0xa6, 0xf5, 0x4b, 0xd2, 0x36, 0x24, 0xbf, 0x31, 0x15, 0x89, 0x8b, 0xde,
	0x30, 0x86, 0xf1, 0x20, 0xb0, 0xad, 0x32, 0x22, 0x48, 0x9d, 0x34, 0xe4, 0x33, 0xde, 0x84, 0x42,
	0xac, 0x2b, 0x47, 0xf2, 0x67, 0xd2, 0x15, 0xcb, 0xc1, 0x4b, 0x50, 0xdc, 0xee, 0x30, 0x53, 0x6c,
	0xed, 0x98, 0x9d, 0x80, 0x96, 0xf3, 0x04, 0xa9, 0x39, 0x03, 0xe4, 0xd1, 0xe3, 0xf0, 0x04, 0x5f,
	0x85, 0x29, 0x8b, 0x05, 0x8d, 0x0e, 0x8d, 0x29, 0xc6, 0x09, 0x52, 0x91, 0x51, 0x8c, 0xce, 0x22,
	0x92, 0x25, 0x28, 0xda, 0xae, 0xf8, 0xee, 0xad, 0x98, 0xe2, 0x1c, 0x41, 0x6a, 0xde, 0x00, 0x79,
	0x94, 0xca, 0x08, 0xb2, 0x14, 0x05, 0x82, 0xd4, 0x71, 0xa3, 0x18, 0x64, 0x48, 0x22, 0x19, 0x37,
	0xab, 0x31, 0xc5, 0x79, 0x82, 0xd4, 0x73, 0x52, 0xc6, 0xcd, 0x6a, 0x44, 0xf0, 0x1a, 0x4c, 0x6f,
	0xdb, 0xbb, 0xd4, 0x4a, 0x85, 0x4c, 0x10, 0xa4, 0x16, 0x8c, 0xa9, 0xf8, 0xb0, 0x97, 0x28, 0x95,
	0x33, 0x49, 0x90, 0x7a, 0x3e, 0x26, 0x4a, 0x24, 0xbd, 0x02, 0xd0, 0x60, 0xac, 0x13, 0x53, 0x00,
	0x41, 0xea, 0x84, 0x31, 0x19, 0x9e, 0xa4, 0x60, 0xb9, 0xf0, 0x6d, 0xb7, 0x15, 0x13, 0x14, 0xa5,
	0xff, 0x8b, 0xd1, 0x59, 0x0a, 0xb6, 0xd1, 0x15, 0x94, 0xc7, 0x14, 0xaf, 0x10, 0xa4, 0x4e, 0x19,
	0x20, 0x8f, 0x7a, 0x0c, 0x4e, 0x61, 0x4c, 0x13, 0xa4, 0x4e, 0x47, 0x06, 0x27, 0x28, 0x7e, 0x00,
	0x40, 0xdd, 0xc0, 0x89, 0x09, 0x66, 0x08, 0x52, 0x67, 0xaa, 0xd7, 0x87, 0x86, 0x73, 0x23, 0x70,
	0xa8, 0x6f, 0x37, 0xeb, 0x6e, 0xe0, 0x18, 0x93, 0x21, 0x7f, 0x24, 0xec, 0x75, 0x98, 0xe1, 0xbd,
	0x86, 0xcf, 0x12, 0xa4, 0xce, 0x1a, 0xd3, 0xbc, 0xc7, 0xf2, 0x94, 0x2c, 0x75, 0x62, 0x89, 0x20,
	0xb5, 0x94, 0x90, 0x65, 0xc2, 0xc5, 0xb3, 0xe8, 0xe7, 0x08, 0x52, 0xe7, 0x8c, 0x22, 0xcf, 0xa0,
	0x8f, 0x49, 0x52, 0x39, 0x98, 0x20, 0x15, 0x47, 0x24, 0x89, 0x94, 0x2a, 0x5c, 0xf4, 0xa9, 0x47,
	0x4d, 0x41, 0xad, 0xad, 0x1e, 0x87, 0xce, 0x93, 0xbc, 0x3a, 0x69, 0xcc, 0x27, 0x97, 0x8f, 0x32,
	0x8e, 0xbd, 0x0d, 0x45, 0xe6, 0xd2, 0xb0, 0x0b, 0x85, 0x4d, 0xa2, 0x7c, 0x41, 0x16, 0xd4, 0x82,
	0x16, 0x15, 0xb3, 0x96, 0x14, 0xb3, 0x56, 0x0f, 0x6f, 0xef, 0x8d, 0x19, 0x20, 0x89, 0xe5, 0x1b,
	0x7e, 0x0d, 0xa6, 0x22, 0xd6, 0x48, 0x57, 0xf9, 0x62, 0x18, 0xb6, 0x7b, 0x63, 0x46, 0x24, 0x30,
	0x52, 0x82, 0x9f, 0xc1, 0xa4, 0x63, 0x7a, 0x31, 0x8e, 0x05, 0x59, 0x42, 0x6f, 0x8f, 0x5e, 0x42,
	0xf7, 0x4d, 0x4f, 0xc2, 0xad, 0xbb, 0xc2, 0xef, 0x1a, 0x13, 0x4e, 0xfc, 0x8a, 0x77, 0x61, 0xde,
	0x31, 0x3d, 0xaf, 0xdf, 0xde, 0x4b, 0x52, 0xcf, 0xbd, 0x53, 0xe9, 0xf1, 0x7a, 0xfc, 0x13, 0x29,
	0x9c, 0x73, 0xfa, 0xcf, 0x33, 0x9a, 0xa3, 0xb2, 0x8e, 0x35, 0x97, 0xcf, 0xa6, 0x39, 0x6a, 0x15,
	0x47, 0x35, 0x67, 0xce, 0xf1, 0x2a, 0x94, 0x5d, 0xe6, 0xde, 0x61, 0xee, 0x0e, 0x75, 0xc3, 0x8e,
	0x69, 0x76, 0x36, 0x4c, 0x27, 0xea, 0x0b, 0xe5, 0x8a, 0xac, 0x9c, 0x81, 0xf7, 0xf8, 0x0e, 0xcc,
	0xa6, 0x6d, 0x39, 0x46, 0x7c, 0x45, 0x46, 0xbc, 0x72, 0x24, 0xe2, 0x1f, 0x24, 0x74, 0xc6, 0x4c,
	0xca, 0x12, 0x09, 0x79, 0x06, 0x69, 0x26, 0x6d, 0x65, 0x0a, 0x6a, 0x91, 0xe4, 0x47, 0x2e, 0xa8,
	0xb9, 0x44, 0x50, 0x3d, 0x29, 0xac, 0xca, 0x1f, 0x10, 0x14, 0x0e, 0xfb, 0xb1, 0x6b, 0x3a, 0x34,
	0xe9, 0xc7, 0xe1, 0x33, 0x5e, 0x80, 0x82, 0xe9, 0xb0, 0xc0, 0x15, 0xe5, 0x9c, 0xac, 0xf0, 0xf8,
	0x0d, 0x3f, 0x84, 0x1c, 0x7b, 0x2e, 0x9b, 0xe9, 0x4c, 0xb5, 0x76, 0xda, 0x1e, 0xad, 0xad, 0x53,
	0xea, 0x49, 0x60, 0x39, 0xf6, 0x5c, 0x59, 0x82, 0x89, 0xe4, 0x1d, 0x4f, 0xc2, 0xb9, 0x77, 0x6b,
	0xef, 0x3f, 0xaa, 0x97, 0xc6, 0xf0, 0x04, 0x8c, 0x7f, 0x60, 0x7c, 0x58, 0x2f, 0xa1, 0x8a, 0x0d,
	0xd3, 0x3d, 0x89, 0x89, 0x4b, 0x90, 0x7f, 0x4e, 0xbb, 0x31, 0xde, 0xf0, 0x11, 0xaf, 0xc1, 0xb9,
	0xc8, 0x3b, 0xb9, 0x53, 0xb4, 0x9b, 0x88, 0x75, 0x35, 0xf7, 0x16, 0xaa, 0xac, 0xc3, 0xc2, 0xf1,
	0xb9, 0x79, 0x8c, 0xce, 0x0b, 0x59, 0x9d, 0x93, 0x59, 0x29, 0x3f, 0x4b, 0xa4, 0xf4, 0xe7, 0xd9,
	0x31, 0x52, 0x36, 0xb2, 0x52, 0xce, 0x32, 0xf7, 0x0e, 0xf5, 0xaf, 0xfe, 0xe8, 0xa0, 0xf6, 0x64,
	0xf9, 0x31, 0x5c, 0x7b, 0xd7, 0x76, 0x2d, 0xc2, 0x02, 0x41, 0x1c, 0xe6, 0x53, 0x62, 0x36, 0xc2,
	0xc7, 0x23, 0xc3, 0x5e, 0x6b, 0x0b, 0xe1, 0xf1, 0x55, 0x5d, 0x6f, 0xd9, 0xa2, 0x1d, 0x34, 0xb4,
	0x26, 0x73, 0xf4, 0x10, 0xc3, 0x0a, 0x6d, 0x32, 0xde, 0xe5, 0x82, 0xc6, 0xaf, 0x31, 0xa4, 0xb5,
	0xe9, 0xa4, 0x93, 0x49, 0x7d, 0xca, 0x9f, 0xa6, 0xa0, 0xdc, 0x2f, 0xf3, 0x91, 0xe9, 0x72, 0x19,
	0x4e, 0x7a, 0xfc, 0x22, 0xf1, 0xce, 0xc8, 0x46, 0x26, 0x12, 0x4f, 0xbe, 0x50, 0x3c, 0xe9, 0x5b,
	0x28, 0xce, 0xae, 0xf3, 0xe5, 0x62, 0xf1, 0x35, 0x2f, 0x16, 0x2f, 0x77, 0x81, 0x93, 0xed, 0x02,
	0x3f, 0x47, 0xff, 0x6f, 0x5c, 0x6f, 0x9e, 0xbe, 0x10, 0x4e, 0x3e, 0xb6, 0x33, 0x10, 0x8e, 0x99,
	0xdb, 0x67, 0x86, 0xf0, 0x4d, 0x98, 0xdf, 0x95, 0x5b, 0xa7, 0x19, 0xb0, 0x5f, 0xd2, 0x04, 0xfa,
	0x14, 0x8d, 0x30, 0x82, 0x1e, 0xf7, 0x8e, 0xa0, 0xb3, 0x77, 0xca, 0x43, 0x20, 0xfd, 0xd3, 0xa2,
	0x02, 0xe3, 0x6b, 0xcc, 0xea, 0x1e, 0xe7, 0x11, 0xe5, 0x19, 0xcc, 0xde, 0x8f, 0x3e, 0x75, 0x7f,
	0x68, 0x8b, 0xb6, 0x24, 0x9b, 0x81, 0x5c, 0xda, 0xd6, 0x73, 0xb6, 0x85, 0x6f, 0xc3, 0xb8, 0x65,
	0x0a, 0x33, 0x06, 0xfa, 0xfa, 0x50, 0xa0, 0xa1, 0x10, 0x43, 0xb2, 0x2c, 0x13, 0x28, 0x66, 0x66,
	0x7e, 0xb8, 0x5d, 0x3c, 0xad, 0x1b, 0x0f, 0x4a, 0x63, 0xf8, 0x3c, 0xe4, 0x1f, 0x6c, 0xd4, 0x4b,
	0xa8, 0xfa, 0xab, 0x32, 0x5c, 0x3a, 0x62, 0x19, 0xf5, 0x77, 0xec, 0x26, 0xc5, 0x9f, 0xe5, 0xa1,
	0x70, 0xc7, 0x0f, 0x2b, 0x19, 0xdf, 0x18, 0xd9, 0x3d, 0x95, 0xd1, 0x59, 0x94, 0xcf, 0x73, 0xbf,
	0xf8, 0xd7, 0x7f, 0x7e, 0x93, 0xfb, 0x7d, 0x4e, 0xf9, 0x5d, 0x4e, 0xdf, 0xb9, 0x91, 0xfc, 0x9e,
	0x71, 0xdc, 0xaf, 0x19, 0xfa, 0x5e, 0x66, 0x1c, 0xed, 0xeb, 0x7b, 0xd9, 0xd9, 0xb3, 0xaf, 0xef,
	0x65, 0x1a, 0xd8, 0xbe, 0xce, 0xa9, 0x67, 0xfa, 0xa6, 0x60, 0xbe, 0xbe, 0x17, 0xf4, 0x5c, 0xec,
	0x65, 0x5a, 0xe1, 0xbe, 0xbe, 0xd7, 0xd3, 0x3f, 0x93, 0xf7, 0xcc, 0xfd, 0xe1, 0x34, 0xd8, 0xd7,
	0xf7, 0xb2, 0x4d, 0xe6, 0x7b, 0x5c, 0xf8, 0x9e, 0x4f, 0xb7, 0xed, 0x5d, 0x7d, 0x79, 0x3f, 0x52,
	0x92, 0x61, 0xe3, 0xfd, 0x72, 0x78, 0xbf, 0x22, 0xde, 0xc7, 0xd0, 0x0b, 0x72, 0x50, 0xc1, 0xee,
	0xe3, 0xcf, 0x10, 0x40, 0x14, 0x20, 0x99, 0x38, 0x5f, 0x4d, 0x90, 0x96, 0x65, 0x8c, 0xae, 0x29,
	0x4b, 0x43, 0x22, 0xb4, 0x8a, 0x96, 0xf1, 0x17, 0x79, 0x98, 0x89, 0x00, 0xa6, 0xdb, 0xd1, 0xed,
	0x53, 0x17, 0x5a, 0xe5, 0xf4, 0xac, 0xca, 0x5f, 0xa3, 0xcc, 0xfa, 0x73, 0x4e, 0xf9, 0x7c, 0x58,
	0x66, 0x6d, 0x71, 0xd3, 0xe5, 0xf2, 0xdb, 0xe3, 0x65, 0x8e, 0xd1, 0x7d, 0xfc, 0x05, 0x02, 0x7c,
	0x98, 0x63, 0x5f, 0x73, 0x18, 0x6f, 0xc9, 0x28, 0x6a, 0xca, 0x1b, 0x27, 0x8e, 0x61, 0x98, 0x85,
	0x3f, 0x85, 0xc2, 0xfb, 0x8c, 0x3d, 0x0f, 0x3c, 0x3c, 0xab, 0xf1, 0xa0, 0x51, 0xd5, 0xde, 0xb3,
	0xe2, 0x9e, 0x7b, 0x9a, 0xfc, 0xd7, 0x24, 0x06, 0x15, 0x7f, 0x6b, 0x68, 0x87, 0x0a, 0x57, 0xf2,
	0x7d, 0xfc, 0x29, 0x82, 0xc2, 0x87, 0x9e, 0x75, 0xca, 0x2e, 0x3a, 0x60, 0x43, 0x52, 0x6e, 0x48,
	0x14, 0xdf, 0xa9, 0x9c, 0x10, 0x45, 0xe8, 0x06, 0x13, 0x0a, 0xeb, 0xb4, 0x43, 0x05, 0x3d, 0xea,
	0x86, 0x41, 0x5a, 0x62, 0x5b, 0x97, 0x4f, 0x6a, 0xeb, 0xbf, 0x11, 0x4c, 0xdc, 0xa5, 0xe2, 0x61,
	0x40, 0xfd, 0xee, 0x97, 0x69, 0xed, 0xaf, 0xd1, 0x41, 0xcd, 0x50, 0x36, 0x60, 0xf1, 0xb8, 0x8f,
	0xbb, 0x54, 0xe1, 0x88, 0x1f, 0x75, 0x4f, 0x50, 0x94, 0x4d, 0xf8, 0xfa, 0x30, 0xeb, 0x7e, 0x12,
	0x8a, 0x4f, 0x6c, 0xfc, 0x67, 0x0e, 0xc6, 0xeb, 0xcd, 0x36, 0xc3, 0xea, 0x00, 0xfb, 0x78, 0xd0,
	0xd0, 0xa2, 0x3d, 0x26, 0x71, 0xef, 0x89, 0x29, 0x95, 0xff, 0xa2, 0x83, 0xda, 0x27, 0x08, 0xa6,
	0x68, 0xb3, 0xcd, 0x08, 0x8f, 0xe6, 0x30, 0x4c, 0xc8, 0x37, 0xdf, 0x6b, 0xe2, 0xb9, 0x47, 0x81,
	0xe3, 0x98, 0x7e, 0x77, 0x95, 0xd4, 0xe3, 0xa3, 0x4a, 0x69, 0x9d, 0xf2, 0xa6, 0x6f, 0xcb, 0xdf,
	0xba, 0xe5, 0xa9, 0xb2, 0x0e, 0xb8, 0xd7, 0x4d, 0x12, 0xed, 0x88, 0xce, 0x91, 0xae, 0xf9, 0x68,
	0xb8, 0x6b, 0x42, 0x68, 0xfa, 0x5e, 0xd4, 0x46, 0x9e, 0x5e, 0x56, 0x4a, 0xfa, 0x4e, 0x35, 0xa5,
	0x0f, 0xef, 0x56, 0xa3, 0xb5, 0xe8, 0x29, 0xc6, 0x47, 0xae, 0xf0, 0x5f, 0x10, 0x4c, 0xad, 0x53,
	0xea, 0x6d, 0x9a, 0xa2, 0x2d, 0x31, 0x7e, 0x35, 0x03, 0xec, 0x6d, 0x69, 0xdb, 0x6d, 0xe5, 0xd6,
	0xd0, 0xa4, 0xee, 0xf9, 0x8c, 0xd7, 0xc2, 0x7d, 0x4d, 0x16, 0x52, 0x0d, 0x60, 0x83, 0xad, 0xd9,
	0xae, 0x65, 0xbb, 0x2d, 0x8e, 0x2f, 0x1f, 0xc9, 0xd9, 0xf5, 0xf8, 0xbf, 0x1e, 0x03, 0xd3, 0x79,
	0x0c, 0x3f, 0x86, 0xf3, 0xe1, 0x0e, 0xcd, 0x02, 0x81, 0x07, 0x10, 0x0d, 0x64, 0xbe, 0x22, 0xe1,
	0x5f, 0xc4, 0xf3, 0x59, 0x7f, 0x8a, 0x58, 0x58, 0x1b, 0x4a, 0x75, 0xdf, 0x67, 0x7e, 0xb8, 0x4c,
	0xae, 0x53, 0x61, 0xda, 0x1d, 0x3e, 0xb2, 0x82, 0x6b, 0x52, 0xc1, 0xab, 0x78, 0xb1, 0x27, 0x60,
	0xa1, 0xd4, 0x17, 0xb6, 0x68, 0x5b, 0xb1, 0xd4, 0x5f, 0x22, 0xc0, 0x77, 0xa9, 0xe8, 0x5f, 0x5e,
	0xdf, 0x1c, 0x1a, 0x8f, 0x3e, 0x8e, 0x81, 0x30, 0xbe, 0x2d, 0x61, 0x5c, 0x55, 0x2e, 0x67, 0x61,
	0x84, 0x08, 0x1a, 0xcc, 0xea, 0xea, 0x7b, 0x61, 0x53, 0x93, 0x4b, 0x2e, 0xfe, 0x04, 0xc1, 0xdc,
	0x26, 0xe3, 0x22, 0x94, 0x28, 0x59, 0x25, 0x90, 0x93, 0xed, 0xc9, 0x03, 0xb5, 0xeb, 0x52, 0xfb,
	0x1b, 0xca, 0xb5, 0xac, 0x76, 0x8f, 0x71, 0x11, 0x22, 0x90, 0x9f, 0xb0, 0x11, 0x8c, 0x24, 0x29,
	0x2a, 0xff, 0x40, 0x07, 0xb5, 0xbf, 0x21, 0xbc, 0x3d, 0x60, 0x99, 0x26, 0x56, 0xa6, 0x4c, 0x57,
	0x56, 0xc8, 0x8b, 0xb6, 0xdd, 0x6c, 0x13, 0xde, 0x66, 0x41, 0xc7, 0x22, 0x2e, 0x13, 0xa4, 0x41,
	0x49, 0xc0, 0xa9, 0x45, 0x6c, 0x97, 0x78, 0x1d, 0xb3, 0x49, 0x09, 0xdb, 0x26, 0xa2, 0x4d, 0x89,
	0xc5, 0x9a, 0x81, 0x43, 0xdd, 0xe8, 0x1f, 0x58, 0xa4, 0xc9, 0x9c, 0xf0, 0xe5, 0x6a, 0xe5, 0x21,
	0x2c, 0x1d, 0xd7, 0x0b, 0xc3, 0x32, 0x4a, 0xd6, 0xf7, 0x11, 0x2b, 0xbe, 0xfa, 0x63, 0x58, 0xac,
	0xb9, 0x4c, 0xb4, 0xa9, 0x1f, 0x4b, 0x08, 0x1d, 0x9a, 0x49, 0xf4, 0xef, 0xf7, 0xa4, 0xfd, 0xa8,
	0x59, 0x35, 0xb6, 0xf6, 0xc7, 0xdc, 0x41, 0xed, 0xb7, 0x39, 0x2c, 0x60, 0xbe, 0x46, 0xd6, 0x6c,
	0x11, 0x1a, 0x98, 0xa9, 0xca, 0x27, 0x70, 0xa1, 0x65, 0x6c, 0xde, 0x59, 0xb9, 0x1b, 0xa1, 0x21,
	0x9e, 0xcf, 0x3e, 0xa6, 0x4d, 0x31, 0xaa, 0x15, 0x95, 0x92, 0xcb, 0x5c, 0xfa, 0x4e, 0x1c, 0xb1,
	0x90, 0xba, 0x9a, 0xbf, 0xa1, 0xbd, 0xb9, 0x9c, 0x47, 0xb9, 0xf1, 0x6a, 0xc9, 0xf4, 0xbc, 0x8e,
	0xdd, 0x94, 0xae, 0xd4, 0x3f, 0xe6, 0xcc, 0xad, 0x2e, 0x64, 0x4f, 0x76, 0x57, 0xb6, 0x19, 0x5b,
	0x71, 0x6c, 0x87, 0xae, 0x1e, 0xa1, 0x5c, 0x1d, 0x40, 0xe9, 0xbf, 0x07, 0x97, 0xee, 0x1f, 0xfa,
	0x3f, 0x6b, 0xc2, 0xa8, 0xd0, 0x9f, 0x4e, 0xa6, 0xb9, 0xd9, 0x28, 0x48, 0xef, 0xdd, 0xfc, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xd3, 0x19, 0x0c, 0xdc, 0x1d, 0x00, 0x00,
}
