---
swagger: "2.0"
info:
  description: "Generate Unannotated Methods Echo Service\nSimilar to echo_service.proto\
    \ but without annotations and without external configuration.\n\nGenerate Unannotated\
    \ Methods Echo Service API consists of a single service which returns\na message."
  version: "version not set"
  title: "examples/internal/proto/examplepb/generate_unbound_methods.proto"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /grpc.gateway.examples.internal.examplepb.GenerateUnboundMethodsEchoService/Echo:
    post:
      tags:
      - "GenerateUnboundMethodsEchoService"
      summary: "Echo method receives a simple message and returns it."
      description: "The message posted as the id parameter will also be\nreturned."
      operationId: "GenerateUnboundMethodsEchoService_Echo"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/examplepbGenerateUnboundMethodsSimpleMessage"
        x-exportParamName: "Body"
      responses:
        200:
          description: "A successful response."
          schema:
            $ref: "#/definitions/examplepbGenerateUnboundMethodsSimpleMessage"
        default:
          description: "An unexpected error response."
          schema:
            $ref: "#/definitions/runtimeError"
  /grpc.gateway.examples.internal.examplepb.GenerateUnboundMethodsEchoService/EchoBody:
    post:
      tags:
      - "GenerateUnboundMethodsEchoService"
      summary: "EchoBody method receives a simple message and returns it."
      operationId: "GenerateUnboundMethodsEchoService_EchoBody"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/examplepbGenerateUnboundMethodsSimpleMessage"
        x-exportParamName: "Body"
      responses:
        200:
          description: "A successful response."
          schema:
            $ref: "#/definitions/examplepbGenerateUnboundMethodsSimpleMessage"
        default:
          description: "An unexpected error response."
          schema:
            $ref: "#/definitions/runtimeError"
  /grpc.gateway.examples.internal.examplepb.GenerateUnboundMethodsEchoService/EchoDelete:
    post:
      tags:
      - "GenerateUnboundMethodsEchoService"
      summary: "EchoDelete method receives a simple message and returns it."
      operationId: "GenerateUnboundMethodsEchoService_EchoDelete"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/examplepbGenerateUnboundMethodsSimpleMessage"
        x-exportParamName: "Body"
      responses:
        200:
          description: "A successful response."
          schema:
            $ref: "#/definitions/examplepbGenerateUnboundMethodsSimpleMessage"
        default:
          description: "An unexpected error response."
          schema:
            $ref: "#/definitions/runtimeError"
definitions:
  examplepbGenerateUnboundMethodsSimpleMessage:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Id represents the message identifier."
      num:
        type: "string"
        format: "int64"
      duration:
        type: "string"
    description: "GenerateUnboundMethodsSimpleMessage represents a simple message\
      \ sent to the unannotated GenerateUnboundMethodsEchoService service."
    example:
      duration: "duration"
      num: "num"
      id: "id"
  protobufAny:
    type: "object"
    properties:
      type_url:
        type: "string"
      value:
        type: "string"
        format: "byte"
        pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
  runtimeError:
    type: "object"
    properties:
      error:
        type: "string"
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      details:
        type: "array"
        items:
          $ref: "#/definitions/protobufAny"
