openapi: 3.0.1
info:
  title: examples/internal/proto/examplepb/generate_unbound_methods.proto
  description: |-
    Generate Unannotated Methods Echo Service
    Similar to echo_service.proto but without annotations and without external configuration.

    Generate Unannotated Methods Echo Service API consists of a single service which returns
    a message.
  version: version not set
servers:
- url: /
tags:
- name: GenerateUnboundMethodsEchoService
paths:
  /grpc.gateway.examples.internal.proto.examplepb.GenerateUnboundMethodsEchoService/Echo:
    post:
      tags:
      - GenerateUnboundMethodsEchoService
      summary: Echo method receives a simple message and returns it.
      description: |-
        The message posted as the id parameter will also be
        returned.
      operationId: GenerateUnboundMethodsEchoService_Echo
      requestBody:
        description: GenerateUnboundMethodsSimpleMessage represents a simple message
          sent to the unannotated GenerateUnboundMethodsEchoService service.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/examplepbGenerateUnboundMethodsSimpleMessage"
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/examplepbGenerateUnboundMethodsSimpleMessage"
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      x-codegen-request-body-name: body
  /grpc.gateway.examples.internal.proto.examplepb.GenerateUnboundMethodsEchoService/EchoBody:
    post:
      tags:
      - GenerateUnboundMethodsEchoService
      summary: EchoBody method receives a simple message and returns it.
      operationId: GenerateUnboundMethodsEchoService_EchoBody
      requestBody:
        description: GenerateUnboundMethodsSimpleMessage represents a simple message
          sent to the unannotated GenerateUnboundMethodsEchoService service.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/examplepbGenerateUnboundMethodsSimpleMessage"
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/examplepbGenerateUnboundMethodsSimpleMessage"
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      x-codegen-request-body-name: body
  /grpc.gateway.examples.internal.proto.examplepb.GenerateUnboundMethodsEchoService/EchoDelete:
    post:
      tags:
      - GenerateUnboundMethodsEchoService
      summary: EchoDelete method receives a simple message and returns it.
      operationId: GenerateUnboundMethodsEchoService_EchoDelete
      requestBody:
        description: GenerateUnboundMethodsSimpleMessage represents a simple message
          sent to the unannotated GenerateUnboundMethodsEchoService service.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/examplepbGenerateUnboundMethodsSimpleMessage"
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/examplepbGenerateUnboundMethodsSimpleMessage"
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      x-codegen-request-body-name: body
components:
  schemas:
    examplepbGenerateUnboundMethodsSimpleMessage:
      type: object
      properties:
        id:
          type: string
          description: Id represents the message identifier.
        num:
          type: string
          format: int64
        duration:
          type: string
      description: GenerateUnboundMethodsSimpleMessage represents a simple message
        sent to the unannotated GenerateUnboundMethodsEchoService service.
      example:
        duration: duration
        num: num
        id: id
    protobufAny:
      type: object
      properties:
        '@type':
          type: string
      additionalProperties:
        type: object
      x-schema-name: protobufAny
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: "#/components/schemas/protobufAny"
x-original-swagger-version: "2.0"
