// Code generated by go-swagger; DO NOT EDIT.

package echo_service

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/echo/models"
)

// NewEchoServiceEchoStatusParams creates a new EchoServiceEchoStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEchoServiceEchoStatusParams() *EchoServiceEchoStatusParams {
	return &EchoServiceEchoStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEchoServiceEchoStatusParamsWithTimeout creates a new EchoServiceEchoStatusParams object
// with the ability to set a timeout on a request.
func NewEchoServiceEchoStatusParamsWithTimeout(timeout time.Duration) *EchoServiceEchoStatusParams {
	return &EchoServiceEchoStatusParams{
		timeout: timeout,
	}
}

// NewEchoServiceEchoStatusParamsWithContext creates a new EchoServiceEchoStatusParams object
// with the ability to set a context for a request.
func NewEchoServiceEchoStatusParamsWithContext(ctx context.Context) *EchoServiceEchoStatusParams {
	return &EchoServiceEchoStatusParams{
		Context: ctx,
	}
}

// NewEchoServiceEchoStatusParamsWithHTTPClient creates a new EchoServiceEchoStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewEchoServiceEchoStatusParamsWithHTTPClient(client *http.Client) *EchoServiceEchoStatusParams {
	return &EchoServiceEchoStatusParams{
		HTTPClient: client,
	}
}

/*
EchoServiceEchoStatusParams contains all the parameters to send to the API endpoint

	for the echo service echo status operation.

	Typically these are written to a http.Request.
*/
type EchoServiceEchoStatusParams struct {

	/* Body.

	     StatusCheckRequest demonstrates name collision handling.
	It uses Status message from both sub and sub2 packages.
	*/
	Body *models.ExamplepbStatusCheckRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the echo service echo status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EchoServiceEchoStatusParams) WithDefaults() *EchoServiceEchoStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the echo service echo status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EchoServiceEchoStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the echo service echo status params
func (o *EchoServiceEchoStatusParams) WithTimeout(timeout time.Duration) *EchoServiceEchoStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the echo service echo status params
func (o *EchoServiceEchoStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the echo service echo status params
func (o *EchoServiceEchoStatusParams) WithContext(ctx context.Context) *EchoServiceEchoStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the echo service echo status params
func (o *EchoServiceEchoStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the echo service echo status params
func (o *EchoServiceEchoStatusParams) WithHTTPClient(client *http.Client) *EchoServiceEchoStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the echo service echo status params
func (o *EchoServiceEchoStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the echo service echo status params
func (o *EchoServiceEchoStatusParams) WithBody(body *models.ExamplepbStatusCheckRequest) *EchoServiceEchoStatusParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the echo service echo status params
func (o *EchoServiceEchoStatusParams) SetBody(body *models.ExamplepbStatusCheckRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *EchoServiceEchoStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
