// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/proto/examplepb/non_standard_names.proto

package examplepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NonStandardMessage has oddly named fields.
type NonStandardMessage struct {
	// Id represents the message identifier.
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Num                  int64                     `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	LineNum              int64                     `protobuf:"varint,3,opt,name=line_num,json=lineNum,proto3" json:"line_num,omitempty"`
	LangIdent            string                    `protobuf:"bytes,4,opt,name=langIdent,proto3" json:"langIdent,omitempty"`
	STATUS               string                    `protobuf:"bytes,5,opt,name=STATUS,proto3" json:"STATUS,omitempty"`
	En_GB                int64                     `protobuf:"varint,6,opt,name=en_GB,json=enGB,proto3" json:"en_GB,omitempty"`
	No                   string                    `protobuf:"bytes,7,opt,name=no,proto3" json:"no,omitempty"`
	Thing                *NonStandardMessage_Thing `protobuf:"bytes,8,opt,name=thing,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NonStandardMessage) Reset()         { *m = NonStandardMessage{} }
func (m *NonStandardMessage) String() string { return proto.CompactTextString(m) }
func (*NonStandardMessage) ProtoMessage()    {}
func (*NonStandardMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ad8828f19375, []int{0}
}

func (m *NonStandardMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonStandardMessage.Unmarshal(m, b)
}
func (m *NonStandardMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonStandardMessage.Marshal(b, m, deterministic)
}
func (m *NonStandardMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonStandardMessage.Merge(m, src)
}
func (m *NonStandardMessage) XXX_Size() int {
	return xxx_messageInfo_NonStandardMessage.Size(m)
}
func (m *NonStandardMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NonStandardMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NonStandardMessage proto.InternalMessageInfo

func (m *NonStandardMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NonStandardMessage) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *NonStandardMessage) GetLineNum() int64 {
	if m != nil {
		return m.LineNum
	}
	return 0
}

func (m *NonStandardMessage) GetLangIdent() string {
	if m != nil {
		return m.LangIdent
	}
	return ""
}

func (m *NonStandardMessage) GetSTATUS() string {
	if m != nil {
		return m.STATUS
	}
	return ""
}

func (m *NonStandardMessage) GetEn_GB() int64 {
	if m != nil {
		return m.En_GB
	}
	return 0
}

func (m *NonStandardMessage) GetNo() string {
	if m != nil {
		return m.No
	}
	return ""
}

func (m *NonStandardMessage) GetThing() *NonStandardMessage_Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type NonStandardMessage_Thing struct {
	SubThing             *NonStandardMessage_Thing_SubThing `protobuf:"bytes,1,opt,name=subThing,proto3" json:"subThing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *NonStandardMessage_Thing) Reset()         { *m = NonStandardMessage_Thing{} }
func (m *NonStandardMessage_Thing) String() string { return proto.CompactTextString(m) }
func (*NonStandardMessage_Thing) ProtoMessage()    {}
func (*NonStandardMessage_Thing) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ad8828f19375, []int{0, 0}
}

func (m *NonStandardMessage_Thing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonStandardMessage_Thing.Unmarshal(m, b)
}
func (m *NonStandardMessage_Thing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonStandardMessage_Thing.Marshal(b, m, deterministic)
}
func (m *NonStandardMessage_Thing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonStandardMessage_Thing.Merge(m, src)
}
func (m *NonStandardMessage_Thing) XXX_Size() int {
	return xxx_messageInfo_NonStandardMessage_Thing.Size(m)
}
func (m *NonStandardMessage_Thing) XXX_DiscardUnknown() {
	xxx_messageInfo_NonStandardMessage_Thing.DiscardUnknown(m)
}

var xxx_messageInfo_NonStandardMessage_Thing proto.InternalMessageInfo

func (m *NonStandardMessage_Thing) GetSubThing() *NonStandardMessage_Thing_SubThing {
	if m != nil {
		return m.SubThing
	}
	return nil
}

type NonStandardMessage_Thing_SubThing struct {
	SubValue             string   `protobuf:"bytes,1,opt,name=sub_value,json=subValue,proto3" json:"sub_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonStandardMessage_Thing_SubThing) Reset()         { *m = NonStandardMessage_Thing_SubThing{} }
func (m *NonStandardMessage_Thing_SubThing) String() string { return proto.CompactTextString(m) }
func (*NonStandardMessage_Thing_SubThing) ProtoMessage()    {}
func (*NonStandardMessage_Thing_SubThing) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ad8828f19375, []int{0, 0, 0}
}

func (m *NonStandardMessage_Thing_SubThing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonStandardMessage_Thing_SubThing.Unmarshal(m, b)
}
func (m *NonStandardMessage_Thing_SubThing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonStandardMessage_Thing_SubThing.Marshal(b, m, deterministic)
}
func (m *NonStandardMessage_Thing_SubThing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonStandardMessage_Thing_SubThing.Merge(m, src)
}
func (m *NonStandardMessage_Thing_SubThing) XXX_Size() int {
	return xxx_messageInfo_NonStandardMessage_Thing_SubThing.Size(m)
}
func (m *NonStandardMessage_Thing_SubThing) XXX_DiscardUnknown() {
	xxx_messageInfo_NonStandardMessage_Thing_SubThing.DiscardUnknown(m)
}

var xxx_messageInfo_NonStandardMessage_Thing_SubThing proto.InternalMessageInfo

func (m *NonStandardMessage_Thing_SubThing) GetSubValue() string {
	if m != nil {
		return m.SubValue
	}
	return ""
}

type NonStandardUpdateRequest struct {
	Body                 *NonStandardMessage   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NonStandardUpdateRequest) Reset()         { *m = NonStandardUpdateRequest{} }
func (m *NonStandardUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*NonStandardUpdateRequest) ProtoMessage()    {}
func (*NonStandardUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ad8828f19375, []int{1}
}

func (m *NonStandardUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonStandardUpdateRequest.Unmarshal(m, b)
}
func (m *NonStandardUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonStandardUpdateRequest.Marshal(b, m, deterministic)
}
func (m *NonStandardUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonStandardUpdateRequest.Merge(m, src)
}
func (m *NonStandardUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_NonStandardUpdateRequest.Size(m)
}
func (m *NonStandardUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NonStandardUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NonStandardUpdateRequest proto.InternalMessageInfo

func (m *NonStandardUpdateRequest) GetBody() *NonStandardMessage {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *NonStandardUpdateRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

// NonStandardMessageWithJSONNames maps odd field names to odd JSON names for maximum confusion.
type NonStandardMessageWithJSONNames struct {
	// Id represents the message identifier.
	Id                   string                                 `protobuf:"bytes,1,opt,name=id,json=ID,proto3" json:"id,omitempty"`
	Num                  int64                                  `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	LineNum              int64                                  `protobuf:"varint,3,opt,name=line_num,json=LineNum,proto3" json:"line_num,omitempty"`
	LangIdent            string                                 `protobuf:"bytes,4,opt,name=langIdent,proto3" json:"langIdent,omitempty"`
	STATUS               string                                 `protobuf:"bytes,5,opt,name=STATUS,json=status,proto3" json:"STATUS,omitempty"`
	En_GB                int64                                  `protobuf:"varint,6,opt,name=en_GB,json=En_GB,proto3" json:"en_GB,omitempty"`
	No                   string                                 `protobuf:"bytes,7,opt,name=no,json=yes,proto3" json:"no,omitempty"`
	Thing                *NonStandardMessageWithJSONNames_Thing `protobuf:"bytes,8,opt,name=thing,json=Thingy,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *NonStandardMessageWithJSONNames) Reset()         { *m = NonStandardMessageWithJSONNames{} }
func (m *NonStandardMessageWithJSONNames) String() string { return proto.CompactTextString(m) }
func (*NonStandardMessageWithJSONNames) ProtoMessage()    {}
func (*NonStandardMessageWithJSONNames) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ad8828f19375, []int{2}
}

func (m *NonStandardMessageWithJSONNames) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonStandardMessageWithJSONNames.Unmarshal(m, b)
}
func (m *NonStandardMessageWithJSONNames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonStandardMessageWithJSONNames.Marshal(b, m, deterministic)
}
func (m *NonStandardMessageWithJSONNames) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonStandardMessageWithJSONNames.Merge(m, src)
}
func (m *NonStandardMessageWithJSONNames) XXX_Size() int {
	return xxx_messageInfo_NonStandardMessageWithJSONNames.Size(m)
}
func (m *NonStandardMessageWithJSONNames) XXX_DiscardUnknown() {
	xxx_messageInfo_NonStandardMessageWithJSONNames.DiscardUnknown(m)
}

var xxx_messageInfo_NonStandardMessageWithJSONNames proto.InternalMessageInfo

func (m *NonStandardMessageWithJSONNames) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NonStandardMessageWithJSONNames) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *NonStandardMessageWithJSONNames) GetLineNum() int64 {
	if m != nil {
		return m.LineNum
	}
	return 0
}

func (m *NonStandardMessageWithJSONNames) GetLangIdent() string {
	if m != nil {
		return m.LangIdent
	}
	return ""
}

func (m *NonStandardMessageWithJSONNames) GetSTATUS() string {
	if m != nil {
		return m.STATUS
	}
	return ""
}

func (m *NonStandardMessageWithJSONNames) GetEn_GB() int64 {
	if m != nil {
		return m.En_GB
	}
	return 0
}

func (m *NonStandardMessageWithJSONNames) GetNo() string {
	if m != nil {
		return m.No
	}
	return ""
}

func (m *NonStandardMessageWithJSONNames) GetThing() *NonStandardMessageWithJSONNames_Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type NonStandardMessageWithJSONNames_Thing struct {
	SubThing             *NonStandardMessageWithJSONNames_Thing_SubThing `protobuf:"bytes,1,opt,name=subThing,json=SubThing,proto3" json:"subThing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *NonStandardMessageWithJSONNames_Thing) Reset()         { *m = NonStandardMessageWithJSONNames_Thing{} }
func (m *NonStandardMessageWithJSONNames_Thing) String() string { return proto.CompactTextString(m) }
func (*NonStandardMessageWithJSONNames_Thing) ProtoMessage()    {}
func (*NonStandardMessageWithJSONNames_Thing) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ad8828f19375, []int{2, 0}
}

func (m *NonStandardMessageWithJSONNames_Thing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonStandardMessageWithJSONNames_Thing.Unmarshal(m, b)
}
func (m *NonStandardMessageWithJSONNames_Thing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonStandardMessageWithJSONNames_Thing.Marshal(b, m, deterministic)
}
func (m *NonStandardMessageWithJSONNames_Thing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonStandardMessageWithJSONNames_Thing.Merge(m, src)
}
func (m *NonStandardMessageWithJSONNames_Thing) XXX_Size() int {
	return xxx_messageInfo_NonStandardMessageWithJSONNames_Thing.Size(m)
}
func (m *NonStandardMessageWithJSONNames_Thing) XXX_DiscardUnknown() {
	xxx_messageInfo_NonStandardMessageWithJSONNames_Thing.DiscardUnknown(m)
}

var xxx_messageInfo_NonStandardMessageWithJSONNames_Thing proto.InternalMessageInfo

func (m *NonStandardMessageWithJSONNames_Thing) GetSubThing() *NonStandardMessageWithJSONNames_Thing_SubThing {
	if m != nil {
		return m.SubThing
	}
	return nil
}

type NonStandardMessageWithJSONNames_Thing_SubThing struct {
	SubValue             string   `protobuf:"bytes,1,opt,name=sub_value,json=sub_Value,proto3" json:"sub_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonStandardMessageWithJSONNames_Thing_SubThing) Reset() {
	*m = NonStandardMessageWithJSONNames_Thing_SubThing{}
}
func (m *NonStandardMessageWithJSONNames_Thing_SubThing) String() string {
	return proto.CompactTextString(m)
}
func (*NonStandardMessageWithJSONNames_Thing_SubThing) ProtoMessage() {}
func (*NonStandardMessageWithJSONNames_Thing_SubThing) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ad8828f19375, []int{2, 0, 0}
}

func (m *NonStandardMessageWithJSONNames_Thing_SubThing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonStandardMessageWithJSONNames_Thing_SubThing.Unmarshal(m, b)
}
func (m *NonStandardMessageWithJSONNames_Thing_SubThing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonStandardMessageWithJSONNames_Thing_SubThing.Marshal(b, m, deterministic)
}
func (m *NonStandardMessageWithJSONNames_Thing_SubThing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonStandardMessageWithJSONNames_Thing_SubThing.Merge(m, src)
}
func (m *NonStandardMessageWithJSONNames_Thing_SubThing) XXX_Size() int {
	return xxx_messageInfo_NonStandardMessageWithJSONNames_Thing_SubThing.Size(m)
}
func (m *NonStandardMessageWithJSONNames_Thing_SubThing) XXX_DiscardUnknown() {
	xxx_messageInfo_NonStandardMessageWithJSONNames_Thing_SubThing.DiscardUnknown(m)
}

var xxx_messageInfo_NonStandardMessageWithJSONNames_Thing_SubThing proto.InternalMessageInfo

func (m *NonStandardMessageWithJSONNames_Thing_SubThing) GetSubValue() string {
	if m != nil {
		return m.SubValue
	}
	return ""
}

type NonStandardWithJSONNamesUpdateRequest struct {
	Body                 *NonStandardMessageWithJSONNames `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	UpdateMask           *field_mask.FieldMask            `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *NonStandardWithJSONNamesUpdateRequest) Reset()         { *m = NonStandardWithJSONNamesUpdateRequest{} }
func (m *NonStandardWithJSONNamesUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*NonStandardWithJSONNamesUpdateRequest) ProtoMessage()    {}
func (*NonStandardWithJSONNamesUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ad8828f19375, []int{3}
}

func (m *NonStandardWithJSONNamesUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonStandardWithJSONNamesUpdateRequest.Unmarshal(m, b)
}
func (m *NonStandardWithJSONNamesUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonStandardWithJSONNamesUpdateRequest.Marshal(b, m, deterministic)
}
func (m *NonStandardWithJSONNamesUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonStandardWithJSONNamesUpdateRequest.Merge(m, src)
}
func (m *NonStandardWithJSONNamesUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_NonStandardWithJSONNamesUpdateRequest.Size(m)
}
func (m *NonStandardWithJSONNamesUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NonStandardWithJSONNamesUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NonStandardWithJSONNamesUpdateRequest proto.InternalMessageInfo

func (m *NonStandardWithJSONNamesUpdateRequest) GetBody() *NonStandardMessageWithJSONNames {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *NonStandardWithJSONNamesUpdateRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

func init() {
	proto.RegisterType((*NonStandardMessage)(nil), "grpc.gateway.examples.examplepb.NonStandardMessage")
	proto.RegisterType((*NonStandardMessage_Thing)(nil), "grpc.gateway.examples.examplepb.NonStandardMessage.Thing")
	proto.RegisterType((*NonStandardMessage_Thing_SubThing)(nil), "grpc.gateway.examples.examplepb.NonStandardMessage.Thing.SubThing")
	proto.RegisterType((*NonStandardUpdateRequest)(nil), "grpc.gateway.examples.examplepb.NonStandardUpdateRequest")
	proto.RegisterType((*NonStandardMessageWithJSONNames)(nil), "grpc.gateway.examples.examplepb.NonStandardMessageWithJSONNames")
	proto.RegisterType((*NonStandardMessageWithJSONNames_Thing)(nil), "grpc.gateway.examples.examplepb.NonStandardMessageWithJSONNames.Thing")
	proto.RegisterType((*NonStandardMessageWithJSONNames_Thing_SubThing)(nil), "grpc.gateway.examples.examplepb.NonStandardMessageWithJSONNames.Thing.SubThing")
	proto.RegisterType((*NonStandardWithJSONNamesUpdateRequest)(nil), "grpc.gateway.examples.examplepb.NonStandardWithJSONNamesUpdateRequest")
}

func init() {
	proto.RegisterFile("examples/proto/examplepb/non_standard_names.proto", fileDescriptor_fa36ad8828f19375)
}

var fileDescriptor_fa36ad8828f19375 = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x41, 0x6f, 0xd3, 0x3c,
	0x18, 0xc7, 0x95, 0x66, 0xed, 0x5a, 0x57, 0x7a, 0x5f, 0xe4, 0x21, 0x14, 0xc2, 0xa4, 0x56, 0x95,
	0xd0, 0x7a, 0x21, 0xd1, 0xb2, 0x03, 0x02, 0x84, 0x04, 0x15, 0xac, 0x1a, 0x62, 0xad, 0x94, 0x74,
	0x20, 0x21, 0x41, 0xe4, 0x2c, 0x5e, 0x1a, 0x9a, 0xda, 0xa1, 0x76, 0x3a, 0x7a, 0xe5, 0x13, 0x4c,
	0xe2, 0x0e, 0xdc, 0xf8, 0x0e, 0xf0, 0x31, 0xb8, 0x73, 0xe2, 0x83, 0xa0, 0xd8, 0x69, 0xa9, 0x55,
	0xa1, 0xb1, 0x6e, 0xa7, 0xfa, 0x79, 0x6c, 0xff, 0x9f, 0xe7, 0x6f, 0xff, 0xe2, 0x82, 0x5d, 0xfc,
	0x1e, 0x8d, 0xd3, 0x04, 0x33, 0x3b, 0x9d, 0x50, 0x4e, 0xed, 0x22, 0x4c, 0x03, 0x9b, 0x50, 0xe2,
	0x33, 0x8e, 0x48, 0x88, 0x26, 0xa1, 0x4f, 0xd0, 0x18, 0x33, 0x4b, 0x2c, 0x81, 0x8d, 0x68, 0x92,
	0x1e, 0x5b, 0x11, 0xe2, 0xf8, 0x14, 0xcd, 0xac, 0xf9, 0x7e, 0x6b, 0xb1, 0xd3, 0xdc, 0x8e, 0x28,
	0x8d, 0x12, 0x6c, 0xa3, 0x34, 0xb6, 0x11, 0x21, 0x94, 0x23, 0x1e, 0x53, 0x52, 0x6c, 0x37, 0x9b,
	0xc5, 0xac, 0x88, 0x82, 0xec, 0xc4, 0x3e, 0x89, 0x71, 0x12, 0xfa, 0x63, 0xc4, 0x46, 0x72, 0x45,
	0xeb, 0x4c, 0x07, 0xb0, 0x47, 0x89, 0x57, 0x14, 0x3f, 0xc4, 0x8c, 0xa1, 0x08, 0xc3, 0xff, 0x40,
	0x29, 0x0e, 0x0d, 0xad, 0xa9, 0xb5, 0x6b, 0x6e, 0x29, 0x0e, 0xe1, 0x35, 0xa0, 0xf7, 0xb2, 0xb1,
	0x51, 0x6a, 0x6a, 0x6d, 0xdd, 0xcd, 0x87, 0xf0, 0x26, 0xa8, 0x26, 0x31, 0xc1, 0x3e, 0xc9, 0xc6,
	0x86, 0x2e, 0xd2, 0x9b, 0x79, 0x9c, 0x4f, 0x6d, 0x83, 0x5a, 0x82, 0x48, 0x74, 0x10, 0x62, 0xc2,
	0x8d, 0x0d, 0xa1, 0xf1, 0x27, 0x01, 0x6f, 0x80, 0x8a, 0x37, 0x78, 0x3c, 0x38, 0xf2, 0x8c, 0xb2,
	0x98, 0x2a, 0x22, 0xb8, 0x05, 0xca, 0x98, 0xf8, 0xdd, 0x8e, 0x51, 0x11, 0x6a, 0x1b, 0x98, 0x74,
	0x3b, 0x79, 0x1f, 0x84, 0x1a, 0x9b, 0xb2, 0x0f, 0x42, 0x61, 0x1f, 0x94, 0xf9, 0x30, 0x26, 0x91,
	0x51, 0x6d, 0x6a, 0xed, 0xba, 0x73, 0xcf, 0x3a, 0xe7, 0x7c, 0xac, 0x55, 0x6f, 0xd6, 0x20, 0x17,
	0x70, 0xa5, 0x8e, 0x79, 0xa6, 0x81, 0xb2, 0x48, 0xc0, 0x37, 0xa0, 0xca, 0xb2, 0x40, 0x8c, 0x85,
	0xf1, 0xba, 0xd3, 0x59, 0x5b, 0xdd, 0xf2, 0x0a, 0x25, 0x77, 0xa1, 0x69, 0xee, 0x80, 0xea, 0x3c,
	0x0b, 0x6f, 0x81, 0x1a, 0xcb, 0x02, 0x7f, 0x8a, 0x92, 0x0c, 0x17, 0xa7, 0x9c, 0x2f, 0x7c, 0x91,
	0xc7, 0xad, 0x2f, 0x1a, 0x30, 0x96, 0x84, 0x8f, 0xd2, 0x10, 0x71, 0xec, 0xe2, 0x77, 0x19, 0x66,
	0x1c, 0x76, 0xc1, 0x46, 0x40, 0xc3, 0x59, 0xd1, 0xe1, 0xde, 0x1a, 0x1d, 0xba, 0x42, 0x00, 0x3e,
	0x00, 0xf5, 0x4c, 0x28, 0x0b, 0x1a, 0xc4, 0xcd, 0xd6, 0x1d, 0xd3, 0x92, 0xc0, 0x58, 0x73, 0x60,
	0xac, 0xfd, 0x1c, 0x98, 0x43, 0xc4, 0x46, 0x2e, 0x90, 0xcb, 0xf3, 0x71, 0xeb, 0xbb, 0x0e, 0x1a,
	0xab, 0xca, 0x2f, 0x63, 0x3e, 0x7c, 0xe6, 0xf5, 0x7b, 0xbd, 0x1c, 0x60, 0x15, 0xa1, 0x83, 0x27,
	0xff, 0x86, 0xd0, 0xf3, 0xf5, 0x10, 0x62, 0x1c, 0xf1, 0x8c, 0xc1, 0xeb, 0x2a, 0x42, 0xe5, 0xa7,
	0x79, 0x00, 0xff, 0x5f, 0x62, 0x48, 0x9f, 0x61, 0x06, 0x5f, 0xab, 0x10, 0xed, 0xaf, 0x71, 0x88,
	0x8a, 0xd5, 0x82, 0xa8, 0x8a, 0xf8, 0x99, 0x99, 0x9f, 0x16, 0x48, 0x8d, 0x56, 0x90, 0xea, 0x5f,
	0x4d, 0xad, 0x25, 0xbe, 0xe6, 0x23, 0xb3, 0xbd, 0xc4, 0xd7, 0xf6, 0x2a, 0x5f, 0x22, 0x21, 0x01,
	0xfb, 0xa6, 0x81, 0xdb, 0x4b, 0x65, 0x14, 0x7d, 0x95, 0xb6, 0x81, 0x42, 0xdb, 0xa3, 0xcb, 0x36,
	0x7f, 0x05, 0xe8, 0x39, 0x9f, 0xd5, 0x07, 0xcb, 0xc3, 0x93, 0x69, 0x7c, 0x8c, 0xe1, 0x57, 0x0d,
	0x54, 0x64, 0xef, 0xf0, 0x42, 0x8f, 0x82, 0xe2, 0xd7, 0x5c, 0xe7, 0x7b, 0x6a, 0xdd, 0xf9, 0xf0,
	0xe3, 0xd7, 0xc7, 0xd2, 0x8e, 0xd3, 0xb0, 0xa7, 0xbb, 0xf3, 0x37, 0x5d, 0x79, 0xd1, 0x6d, 0xd9,
	0xfe, 0x7d, 0xe9, 0xfe, 0xa7, 0x06, 0xb6, 0x64, 0x55, 0xf5, 0x7b, 0xb9, 0x10, 0x86, 0x7f, 0xbf,
	0x33, 0xf3, 0xd2, 0xb7, 0xd4, 0x7a, 0x28, 0x0c, 0xdd, 0x75, 0xec, 0x73, 0x0c, 0xf9, 0xa7, 0x31,
	0x1f, 0xfa, 0x6f, 0x19, 0x25, 0xf2, 0x3f, 0x4b, 0x1a, 0xec, 0xd4, 0x5f, 0xd5, 0x16, 0xb5, 0x82,
	0x8a, 0xb8, 0xce, 0xbd, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x18, 0x50, 0x51, 0xb2, 0xfc, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NonStandardServiceClient is the client API for NonStandardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NonStandardServiceClient interface {
	// Apply field mask to empty NonStandardMessage and return result.
	Update(ctx context.Context, in *NonStandardUpdateRequest, opts ...grpc.CallOption) (*NonStandardMessage, error)
	// Apply field mask to empty NonStandardMessageWithJSONNames and return result.
	UpdateWithJSONNames(ctx context.Context, in *NonStandardWithJSONNamesUpdateRequest, opts ...grpc.CallOption) (*NonStandardMessageWithJSONNames, error)
}

type nonStandardServiceClient struct {
	cc *grpc.ClientConn
}

func NewNonStandardServiceClient(cc *grpc.ClientConn) NonStandardServiceClient {
	return &nonStandardServiceClient{cc}
}

func (c *nonStandardServiceClient) Update(ctx context.Context, in *NonStandardUpdateRequest, opts ...grpc.CallOption) (*NonStandardMessage, error) {
	out := new(NonStandardMessage)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.NonStandardService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nonStandardServiceClient) UpdateWithJSONNames(ctx context.Context, in *NonStandardWithJSONNamesUpdateRequest, opts ...grpc.CallOption) (*NonStandardMessageWithJSONNames, error) {
	out := new(NonStandardMessageWithJSONNames)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.NonStandardService/UpdateWithJSONNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NonStandardServiceServer is the server API for NonStandardService service.
type NonStandardServiceServer interface {
	// Apply field mask to empty NonStandardMessage and return result.
	Update(context.Context, *NonStandardUpdateRequest) (*NonStandardMessage, error)
	// Apply field mask to empty NonStandardMessageWithJSONNames and return result.
	UpdateWithJSONNames(context.Context, *NonStandardWithJSONNamesUpdateRequest) (*NonStandardMessageWithJSONNames, error)
}

// UnimplementedNonStandardServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNonStandardServiceServer struct {
}

func (*UnimplementedNonStandardServiceServer) Update(ctx context.Context, req *NonStandardUpdateRequest) (*NonStandardMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedNonStandardServiceServer) UpdateWithJSONNames(ctx context.Context, req *NonStandardWithJSONNamesUpdateRequest) (*NonStandardMessageWithJSONNames, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWithJSONNames not implemented")
}

func RegisterNonStandardServiceServer(s *grpc.Server, srv NonStandardServiceServer) {
	s.RegisterService(&_NonStandardService_serviceDesc, srv)
}

func _NonStandardService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonStandardUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NonStandardServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.NonStandardService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NonStandardServiceServer).Update(ctx, req.(*NonStandardUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NonStandardService_UpdateWithJSONNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonStandardWithJSONNamesUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NonStandardServiceServer).UpdateWithJSONNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.NonStandardService/UpdateWithJSONNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NonStandardServiceServer).UpdateWithJSONNames(ctx, req.(*NonStandardWithJSONNamesUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NonStandardService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.examplepb.NonStandardService",
	HandlerType: (*NonStandardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _NonStandardService_Update_Handler,
		},
		{
			MethodName: "UpdateWithJSONNames",
			Handler:    _NonStandardService_UpdateWithJSONNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/proto/examplepb/non_standard_names.proto",
}
