// Code generated by go-swagger; DO NOT EDIT.

package client

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe/client/a_bit_of_everything"
	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe/client/camel_case_service_name"
	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe/client/echo_rpc"
	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe/client/snake_enum_service"
)

// Default a bit of everything HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https", "wss"}

// NewHTTPClient creates a new a bit of everything HTTP client.
func NewHTTPClient(formats strfmt.Registry) *ABitOfEverything {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new a bit of everything HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *ABitOfEverything {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new a bit of everything client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *ABitOfEverything {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(ABitOfEverything)
	cli.Transport = transport
	cli.ABitOfEverything = a_bit_of_everything.New(transport, formats)
	cli.CamelCaseServiceName = camel_case_service_name.New(transport, formats)
	cli.EchoRPC = echo_rpc.New(transport, formats)
	cli.SnakeEnumService = snake_enum_service.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// ABitOfEverything is a client for a bit of everything
type ABitOfEverything struct {
	ABitOfEverything a_bit_of_everything.ClientService

	CamelCaseServiceName camel_case_service_name.ClientService

	EchoRPC echo_rpc.ClientService

	SnakeEnumService snake_enum_service.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *ABitOfEverything) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.ABitOfEverything.SetTransport(transport)
	c.CamelCaseServiceName.SetTransport(transport)
	c.EchoRPC.SetTransport(transport)
	c.SnakeEnumService.SetTransport(transport)
}
