// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/internal/proto/examplepb/a_bit_of_everything.proto

package examplepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	pathenum "github.com/grpc-ecosystem/grpc-gateway/examples/internal/proto/pathenum"
	sub "github.com/grpc-ecosystem/grpc-gateway/examples/internal/proto/sub"
	sub2 "github.com/grpc-ecosystem/grpc-gateway/examples/internal/proto/sub2"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NumericEnum is one or zero.
type NumericEnum int32

const (
	// ZERO means 0
	NumericEnum_ZERO NumericEnum = 0
	// ONE means 1
	NumericEnum_ONE NumericEnum = 1
)

var NumericEnum_name = map[int32]string{
	0: "ZERO",
	1: "ONE",
}

var NumericEnum_value = map[string]int32{
	"ZERO": 0,
	"ONE":  1,
}

func (x NumericEnum) String() string {
	return proto.EnumName(NumericEnum_name, int32(x))
}

func (NumericEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e6ccf6cab3ab66ab, []int{0}
}

// DeepEnum is one or zero.
type ABitOfEverything_Nested_DeepEnum int32

const (
	// FALSE is false.
	ABitOfEverything_Nested_FALSE ABitOfEverything_Nested_DeepEnum = 0
	// TRUE is true.
	ABitOfEverything_Nested_TRUE ABitOfEverything_Nested_DeepEnum = 1
)

var ABitOfEverything_Nested_DeepEnum_name = map[int32]string{
	0: "FALSE",
	1: "TRUE",
}

var ABitOfEverything_Nested_DeepEnum_value = map[string]int32{
	"FALSE": 0,
	"TRUE":  1,
}

func (x ABitOfEverything_Nested_DeepEnum) String() string {
	return proto.EnumName(ABitOfEverything_Nested_DeepEnum_name, int32(x))
}

func (ABitOfEverything_Nested_DeepEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e6ccf6cab3ab66ab, []int{0, 0, 0}
}

// Intentionally complicated message type to cover many features of Protobuf.
type ABitOfEverything struct {
	SingleNested        *ABitOfEverything_Nested                `protobuf:"bytes,25,opt,name=single_nested,json=singleNested,proto3" json:"single_nested,omitempty"`
	Uuid                string                                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Nested              []*ABitOfEverything_Nested              `protobuf:"bytes,2,rep,name=nested,proto3" json:"nested,omitempty"`
	FloatValue          float32                                 `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue         float64                                 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	Int64Value          int64                                   `protobuf:"varint,5,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint64Value         uint64                                  `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Int32Value          int32                                   `protobuf:"varint,7,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Fixed64Value        uint64                                  `protobuf:"fixed64,8,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	Fixed32Value        uint32                                  `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	BoolValue           bool                                    `protobuf:"varint,10,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	StringValue         string                                  `protobuf:"bytes,11,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BytesValue          []byte                                  `protobuf:"bytes,29,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	Uint32Value         uint32                                  `protobuf:"varint,13,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	EnumValue           NumericEnum                             `protobuf:"varint,14,opt,name=enum_value,json=enumValue,proto3,enum=grpc.gateway.examples.internal.examplepb.NumericEnum" json:"enum_value,omitempty"`
	PathEnumValue       pathenum.PathEnum                       `protobuf:"varint,30,opt,name=path_enum_value,json=pathEnumValue,proto3,enum=grpc.gateway.examples.internal.pathenum.PathEnum" json:"path_enum_value,omitempty"`
	NestedPathEnumValue pathenum.MessagePathEnum_NestedPathEnum `protobuf:"varint,31,opt,name=nested_path_enum_value,json=nestedPathEnumValue,proto3,enum=grpc.gateway.examples.internal.pathenum.MessagePathEnum_NestedPathEnum" json:"nested_path_enum_value,omitempty"`
	Sfixed32Value       int32                                   `protobuf:"fixed32,15,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	Sfixed64Value       int64                                   `protobuf:"fixed64,16,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	Sint32Value         int32                                   `protobuf:"zigzag32,17,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	Sint64Value         int64                                   `protobuf:"zigzag64,18,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	RepeatedStringValue []string                                `protobuf:"bytes,19,rep,name=repeated_string_value,json=repeatedStringValue,proto3" json:"repeated_string_value,omitempty"`
	// Types that are valid to be assigned to OneofValue:
	//	*ABitOfEverything_OneofEmpty
	//	*ABitOfEverything_OneofString
	OneofValue               isABitOfEverything_OneofValue       `protobuf_oneof:"oneof_value"`
	MapValue                 map[string]NumericEnum              `protobuf:"bytes,22,rep,name=map_value,json=mapValue,proto3" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=grpc.gateway.examples.internal.examplepb.NumericEnum"`
	MappedStringValue        map[string]string                   `protobuf:"bytes,23,rep,name=mapped_string_value,json=mappedStringValue,proto3" json:"mapped_string_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MappedNestedValue        map[string]*ABitOfEverything_Nested `protobuf:"bytes,24,rep,name=mapped_nested_value,json=mappedNestedValue,proto3" json:"mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NonConventionalNameValue string                              `protobuf:"bytes,26,opt,name=nonConventionalNameValue,proto3" json:"nonConventionalNameValue,omitempty"`
	TimestampValue           *timestamp.Timestamp                `protobuf:"bytes,27,opt,name=timestamp_value,json=timestampValue,proto3" json:"timestamp_value,omitempty"`
	// repeated enum value. it is comma-separated in query
	RepeatedEnumValue []NumericEnum `protobuf:"varint,28,rep,packed,name=repeated_enum_value,json=repeatedEnumValue,proto3,enum=grpc.gateway.examples.internal.examplepb.NumericEnum" json:"repeated_enum_value,omitempty"`
	// repeated numeric enum comment (This comment is overridden by the field annotation)
	RepeatedEnumAnnotation []NumericEnum `protobuf:"varint,32,rep,packed,name=repeated_enum_annotation,json=repeatedEnumAnnotation,proto3,enum=grpc.gateway.examples.internal.examplepb.NumericEnum" json:"repeated_enum_annotation,omitempty"`
	// numeric enum comment (This comment is overridden by the field annotation)
	EnumValueAnnotation NumericEnum `protobuf:"varint,33,opt,name=enum_value_annotation,json=enumValueAnnotation,proto3,enum=grpc.gateway.examples.internal.examplepb.NumericEnum" json:"enum_value_annotation,omitempty"`
	// repeated string comment (This comment is overridden by the field annotation)
	RepeatedStringAnnotation []string `protobuf:"bytes,34,rep,name=repeated_string_annotation,json=repeatedStringAnnotation,proto3" json:"repeated_string_annotation,omitempty"`
	// repeated nested object comment (This comment is overridden by the field annotation)
	RepeatedNestedAnnotation []*ABitOfEverything_Nested `protobuf:"bytes,35,rep,name=repeated_nested_annotation,json=repeatedNestedAnnotation,proto3" json:"repeated_nested_annotation,omitempty"`
	// nested object comments (This comment is overridden by the field annotation)
	NestedAnnotation     *ABitOfEverything_Nested `protobuf:"bytes,36,opt,name=nested_annotation,json=nestedAnnotation,proto3" json:"nested_annotation,omitempty"`
	Int64OverrideType    int64                    `protobuf:"varint,37,opt,name=int64_override_type,json=int64OverrideType,proto3" json:"int64_override_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ABitOfEverything) Reset()         { *m = ABitOfEverything{} }
func (m *ABitOfEverything) String() string { return proto.CompactTextString(m) }
func (*ABitOfEverything) ProtoMessage()    {}
func (*ABitOfEverything) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6ccf6cab3ab66ab, []int{0}
}

func (m *ABitOfEverything) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ABitOfEverything.Unmarshal(m, b)
}
func (m *ABitOfEverything) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ABitOfEverything.Marshal(b, m, deterministic)
}
func (m *ABitOfEverything) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ABitOfEverything.Merge(m, src)
}
func (m *ABitOfEverything) XXX_Size() int {
	return xxx_messageInfo_ABitOfEverything.Size(m)
}
func (m *ABitOfEverything) XXX_DiscardUnknown() {
	xxx_messageInfo_ABitOfEverything.DiscardUnknown(m)
}

var xxx_messageInfo_ABitOfEverything proto.InternalMessageInfo

func (m *ABitOfEverything) GetSingleNested() *ABitOfEverything_Nested {
	if m != nil {
		return m.SingleNested
	}
	return nil
}

func (m *ABitOfEverything) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ABitOfEverything) GetNested() []*ABitOfEverything_Nested {
	if m != nil {
		return m.Nested
	}
	return nil
}

func (m *ABitOfEverything) GetFloatValue() float32 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *ABitOfEverything) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *ABitOfEverything) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *ABitOfEverything) GetUint64Value() uint64 {
	if m != nil {
		return m.Uint64Value
	}
	return 0
}

func (m *ABitOfEverything) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *ABitOfEverything) GetFixed64Value() uint64 {
	if m != nil {
		return m.Fixed64Value
	}
	return 0
}

func (m *ABitOfEverything) GetFixed32Value() uint32 {
	if m != nil {
		return m.Fixed32Value
	}
	return 0
}

func (m *ABitOfEverything) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *ABitOfEverything) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *ABitOfEverything) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *ABitOfEverything) GetUint32Value() uint32 {
	if m != nil {
		return m.Uint32Value
	}
	return 0
}

func (m *ABitOfEverything) GetEnumValue() NumericEnum {
	if m != nil {
		return m.EnumValue
	}
	return NumericEnum_ZERO
}

func (m *ABitOfEverything) GetPathEnumValue() pathenum.PathEnum {
	if m != nil {
		return m.PathEnumValue
	}
	return pathenum.PathEnum_ABC
}

func (m *ABitOfEverything) GetNestedPathEnumValue() pathenum.MessagePathEnum_NestedPathEnum {
	if m != nil {
		return m.NestedPathEnumValue
	}
	return pathenum.MessagePathEnum_GHI
}

func (m *ABitOfEverything) GetSfixed32Value() int32 {
	if m != nil {
		return m.Sfixed32Value
	}
	return 0
}

func (m *ABitOfEverything) GetSfixed64Value() int64 {
	if m != nil {
		return m.Sfixed64Value
	}
	return 0
}

func (m *ABitOfEverything) GetSint32Value() int32 {
	if m != nil {
		return m.Sint32Value
	}
	return 0
}

func (m *ABitOfEverything) GetSint64Value() int64 {
	if m != nil {
		return m.Sint64Value
	}
	return 0
}

func (m *ABitOfEverything) GetRepeatedStringValue() []string {
	if m != nil {
		return m.RepeatedStringValue
	}
	return nil
}

type isABitOfEverything_OneofValue interface {
	isABitOfEverything_OneofValue()
}

type ABitOfEverything_OneofEmpty struct {
	OneofEmpty *empty.Empty `protobuf:"bytes,20,opt,name=oneof_empty,json=oneofEmpty,proto3,oneof"`
}

type ABitOfEverything_OneofString struct {
	OneofString string `protobuf:"bytes,21,opt,name=oneof_string,json=oneofString,proto3,oneof"`
}

func (*ABitOfEverything_OneofEmpty) isABitOfEverything_OneofValue() {}

func (*ABitOfEverything_OneofString) isABitOfEverything_OneofValue() {}

func (m *ABitOfEverything) GetOneofValue() isABitOfEverything_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *ABitOfEverything) GetOneofEmpty() *empty.Empty {
	if x, ok := m.GetOneofValue().(*ABitOfEverything_OneofEmpty); ok {
		return x.OneofEmpty
	}
	return nil
}

func (m *ABitOfEverything) GetOneofString() string {
	if x, ok := m.GetOneofValue().(*ABitOfEverything_OneofString); ok {
		return x.OneofString
	}
	return ""
}

func (m *ABitOfEverything) GetMapValue() map[string]NumericEnum {
	if m != nil {
		return m.MapValue
	}
	return nil
}

func (m *ABitOfEverything) GetMappedStringValue() map[string]string {
	if m != nil {
		return m.MappedStringValue
	}
	return nil
}

func (m *ABitOfEverything) GetMappedNestedValue() map[string]*ABitOfEverything_Nested {
	if m != nil {
		return m.MappedNestedValue
	}
	return nil
}

func (m *ABitOfEverything) GetNonConventionalNameValue() string {
	if m != nil {
		return m.NonConventionalNameValue
	}
	return ""
}

func (m *ABitOfEverything) GetTimestampValue() *timestamp.Timestamp {
	if m != nil {
		return m.TimestampValue
	}
	return nil
}

func (m *ABitOfEverything) GetRepeatedEnumValue() []NumericEnum {
	if m != nil {
		return m.RepeatedEnumValue
	}
	return nil
}

func (m *ABitOfEverything) GetRepeatedEnumAnnotation() []NumericEnum {
	if m != nil {
		return m.RepeatedEnumAnnotation
	}
	return nil
}

func (m *ABitOfEverything) GetEnumValueAnnotation() NumericEnum {
	if m != nil {
		return m.EnumValueAnnotation
	}
	return NumericEnum_ZERO
}

func (m *ABitOfEverything) GetRepeatedStringAnnotation() []string {
	if m != nil {
		return m.RepeatedStringAnnotation
	}
	return nil
}

func (m *ABitOfEverything) GetRepeatedNestedAnnotation() []*ABitOfEverything_Nested {
	if m != nil {
		return m.RepeatedNestedAnnotation
	}
	return nil
}

func (m *ABitOfEverything) GetNestedAnnotation() *ABitOfEverything_Nested {
	if m != nil {
		return m.NestedAnnotation
	}
	return nil
}

func (m *ABitOfEverything) GetInt64OverrideType() int64 {
	if m != nil {
		return m.Int64OverrideType
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ABitOfEverything) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ABitOfEverything_OneofEmpty)(nil),
		(*ABitOfEverything_OneofString)(nil),
	}
}

// Nested is nested type.
type ABitOfEverything_Nested struct {
	// name is nested field.
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount uint32 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// DeepEnum comment.
	Ok                   ABitOfEverything_Nested_DeepEnum `protobuf:"varint,3,opt,name=ok,proto3,enum=grpc.gateway.examples.internal.examplepb.ABitOfEverything_Nested_DeepEnum" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ABitOfEverything_Nested) Reset()         { *m = ABitOfEverything_Nested{} }
func (m *ABitOfEverything_Nested) String() string { return proto.CompactTextString(m) }
func (*ABitOfEverything_Nested) ProtoMessage()    {}
func (*ABitOfEverything_Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6ccf6cab3ab66ab, []int{0, 0}
}

func (m *ABitOfEverything_Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ABitOfEverything_Nested.Unmarshal(m, b)
}
func (m *ABitOfEverything_Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ABitOfEverything_Nested.Marshal(b, m, deterministic)
}
func (m *ABitOfEverything_Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ABitOfEverything_Nested.Merge(m, src)
}
func (m *ABitOfEverything_Nested) XXX_Size() int {
	return xxx_messageInfo_ABitOfEverything_Nested.Size(m)
}
func (m *ABitOfEverything_Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_ABitOfEverything_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_ABitOfEverything_Nested proto.InternalMessageInfo

func (m *ABitOfEverything_Nested) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ABitOfEverything_Nested) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ABitOfEverything_Nested) GetOk() ABitOfEverything_Nested_DeepEnum {
	if m != nil {
		return m.Ok
	}
	return ABitOfEverything_Nested_FALSE
}

// ABitOfEverythingRepeated is used to validate repeated path parameter functionality
type ABitOfEverythingRepeated struct {
	// repeated values. they are comma-separated in path
	PathRepeatedFloatValue    []float32     `protobuf:"fixed32,1,rep,packed,name=path_repeated_float_value,json=pathRepeatedFloatValue,proto3" json:"path_repeated_float_value,omitempty"`
	PathRepeatedDoubleValue   []float64     `protobuf:"fixed64,2,rep,packed,name=path_repeated_double_value,json=pathRepeatedDoubleValue,proto3" json:"path_repeated_double_value,omitempty"`
	PathRepeatedInt64Value    []int64       `protobuf:"varint,3,rep,packed,name=path_repeated_int64_value,json=pathRepeatedInt64Value,proto3" json:"path_repeated_int64_value,omitempty"`
	PathRepeatedUint64Value   []uint64      `protobuf:"varint,4,rep,packed,name=path_repeated_uint64_value,json=pathRepeatedUint64Value,proto3" json:"path_repeated_uint64_value,omitempty"`
	PathRepeatedInt32Value    []int32       `protobuf:"varint,5,rep,packed,name=path_repeated_int32_value,json=pathRepeatedInt32Value,proto3" json:"path_repeated_int32_value,omitempty"`
	PathRepeatedFixed64Value  []uint64      `protobuf:"fixed64,6,rep,packed,name=path_repeated_fixed64_value,json=pathRepeatedFixed64Value,proto3" json:"path_repeated_fixed64_value,omitempty"`
	PathRepeatedFixed32Value  []uint32      `protobuf:"fixed32,7,rep,packed,name=path_repeated_fixed32_value,json=pathRepeatedFixed32Value,proto3" json:"path_repeated_fixed32_value,omitempty"`
	PathRepeatedBoolValue     []bool        `protobuf:"varint,8,rep,packed,name=path_repeated_bool_value,json=pathRepeatedBoolValue,proto3" json:"path_repeated_bool_value,omitempty"`
	PathRepeatedStringValue   []string      `protobuf:"bytes,9,rep,name=path_repeated_string_value,json=pathRepeatedStringValue,proto3" json:"path_repeated_string_value,omitempty"`
	PathRepeatedBytesValue    [][]byte      `protobuf:"bytes,10,rep,name=path_repeated_bytes_value,json=pathRepeatedBytesValue,proto3" json:"path_repeated_bytes_value,omitempty"`
	PathRepeatedUint32Value   []uint32      `protobuf:"varint,11,rep,packed,name=path_repeated_uint32_value,json=pathRepeatedUint32Value,proto3" json:"path_repeated_uint32_value,omitempty"`
	PathRepeatedEnumValue     []NumericEnum `protobuf:"varint,12,rep,packed,name=path_repeated_enum_value,json=pathRepeatedEnumValue,proto3,enum=grpc.gateway.examples.internal.examplepb.NumericEnum" json:"path_repeated_enum_value,omitempty"`
	PathRepeatedSfixed32Value []int32       `protobuf:"fixed32,13,rep,packed,name=path_repeated_sfixed32_value,json=pathRepeatedSfixed32Value,proto3" json:"path_repeated_sfixed32_value,omitempty"`
	PathRepeatedSfixed64Value []int64       `protobuf:"fixed64,14,rep,packed,name=path_repeated_sfixed64_value,json=pathRepeatedSfixed64Value,proto3" json:"path_repeated_sfixed64_value,omitempty"`
	PathRepeatedSint32Value   []int32       `protobuf:"zigzag32,15,rep,packed,name=path_repeated_sint32_value,json=pathRepeatedSint32Value,proto3" json:"path_repeated_sint32_value,omitempty"`
	PathRepeatedSint64Value   []int64       `protobuf:"zigzag64,16,rep,packed,name=path_repeated_sint64_value,json=pathRepeatedSint64Value,proto3" json:"path_repeated_sint64_value,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}      `json:"-"`
	XXX_unrecognized          []byte        `json:"-"`
	XXX_sizecache             int32         `json:"-"`
}

func (m *ABitOfEverythingRepeated) Reset()         { *m = ABitOfEverythingRepeated{} }
func (m *ABitOfEverythingRepeated) String() string { return proto.CompactTextString(m) }
func (*ABitOfEverythingRepeated) ProtoMessage()    {}
func (*ABitOfEverythingRepeated) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6ccf6cab3ab66ab, []int{1}
}

func (m *ABitOfEverythingRepeated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ABitOfEverythingRepeated.Unmarshal(m, b)
}
func (m *ABitOfEverythingRepeated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ABitOfEverythingRepeated.Marshal(b, m, deterministic)
}
func (m *ABitOfEverythingRepeated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ABitOfEverythingRepeated.Merge(m, src)
}
func (m *ABitOfEverythingRepeated) XXX_Size() int {
	return xxx_messageInfo_ABitOfEverythingRepeated.Size(m)
}
func (m *ABitOfEverythingRepeated) XXX_DiscardUnknown() {
	xxx_messageInfo_ABitOfEverythingRepeated.DiscardUnknown(m)
}

var xxx_messageInfo_ABitOfEverythingRepeated proto.InternalMessageInfo

func (m *ABitOfEverythingRepeated) GetPathRepeatedFloatValue() []float32 {
	if m != nil {
		return m.PathRepeatedFloatValue
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedDoubleValue() []float64 {
	if m != nil {
		return m.PathRepeatedDoubleValue
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedInt64Value() []int64 {
	if m != nil {
		return m.PathRepeatedInt64Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedUint64Value() []uint64 {
	if m != nil {
		return m.PathRepeatedUint64Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedInt32Value() []int32 {
	if m != nil {
		return m.PathRepeatedInt32Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedFixed64Value() []uint64 {
	if m != nil {
		return m.PathRepeatedFixed64Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedFixed32Value() []uint32 {
	if m != nil {
		return m.PathRepeatedFixed32Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedBoolValue() []bool {
	if m != nil {
		return m.PathRepeatedBoolValue
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedStringValue() []string {
	if m != nil {
		return m.PathRepeatedStringValue
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedBytesValue() [][]byte {
	if m != nil {
		return m.PathRepeatedBytesValue
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedUint32Value() []uint32 {
	if m != nil {
		return m.PathRepeatedUint32Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedEnumValue() []NumericEnum {
	if m != nil {
		return m.PathRepeatedEnumValue
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedSfixed32Value() []int32 {
	if m != nil {
		return m.PathRepeatedSfixed32Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedSfixed64Value() []int64 {
	if m != nil {
		return m.PathRepeatedSfixed64Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedSint32Value() []int32 {
	if m != nil {
		return m.PathRepeatedSint32Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedSint64Value() []int64 {
	if m != nil {
		return m.PathRepeatedSint64Value
	}
	return nil
}

type Body struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6ccf6cab3ab66ab, []int{2}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MessageWithBody struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *Body    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWithBody) Reset()         { *m = MessageWithBody{} }
func (m *MessageWithBody) String() string { return proto.CompactTextString(m) }
func (*MessageWithBody) ProtoMessage()    {}
func (*MessageWithBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6ccf6cab3ab66ab, []int{3}
}

func (m *MessageWithBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithBody.Unmarshal(m, b)
}
func (m *MessageWithBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithBody.Marshal(b, m, deterministic)
}
func (m *MessageWithBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithBody.Merge(m, src)
}
func (m *MessageWithBody) XXX_Size() int {
	return xxx_messageInfo_MessageWithBody.Size(m)
}
func (m *MessageWithBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithBody.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithBody proto.InternalMessageInfo

func (m *MessageWithBody) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageWithBody) GetData() *Body {
	if m != nil {
		return m.Data
	}
	return nil
}

// UpdateV2Request request for update includes the message and the update mask
type UpdateV2Request struct {
	Abe                  *ABitOfEverything     `protobuf:"bytes,1,opt,name=abe,proto3" json:"abe,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateV2Request) Reset()         { *m = UpdateV2Request{} }
func (m *UpdateV2Request) String() string { return proto.CompactTextString(m) }
func (*UpdateV2Request) ProtoMessage()    {}
func (*UpdateV2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6ccf6cab3ab66ab, []int{4}
}

func (m *UpdateV2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateV2Request.Unmarshal(m, b)
}
func (m *UpdateV2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateV2Request.Marshal(b, m, deterministic)
}
func (m *UpdateV2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateV2Request.Merge(m, src)
}
func (m *UpdateV2Request) XXX_Size() int {
	return xxx_messageInfo_UpdateV2Request.Size(m)
}
func (m *UpdateV2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateV2Request.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateV2Request proto.InternalMessageInfo

func (m *UpdateV2Request) GetAbe() *ABitOfEverything {
	if m != nil {
		return m.Abe
	}
	return nil
}

func (m *UpdateV2Request) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

func init() {
	proto.RegisterEnum("grpc.gateway.examples.internal.examplepb.NumericEnum", NumericEnum_name, NumericEnum_value)
	proto.RegisterEnum("grpc.gateway.examples.internal.examplepb.ABitOfEverything_Nested_DeepEnum", ABitOfEverything_Nested_DeepEnum_name, ABitOfEverything_Nested_DeepEnum_value)
	proto.RegisterType((*ABitOfEverything)(nil), "grpc.gateway.examples.internal.examplepb.ABitOfEverything")
	proto.RegisterMapType((map[string]NumericEnum)(nil), "grpc.gateway.examples.internal.examplepb.ABitOfEverything.MapValueEntry")
	proto.RegisterMapType((map[string]*ABitOfEverything_Nested)(nil), "grpc.gateway.examples.internal.examplepb.ABitOfEverything.MappedNestedValueEntry")
	proto.RegisterMapType((map[string]string)(nil), "grpc.gateway.examples.internal.examplepb.ABitOfEverything.MappedStringValueEntry")
	proto.RegisterType((*ABitOfEverything_Nested)(nil), "grpc.gateway.examples.internal.examplepb.ABitOfEverything.Nested")
	proto.RegisterType((*ABitOfEverythingRepeated)(nil), "grpc.gateway.examples.internal.examplepb.ABitOfEverythingRepeated")
	proto.RegisterType((*Body)(nil), "grpc.gateway.examples.internal.examplepb.Body")
	proto.RegisterType((*MessageWithBody)(nil), "grpc.gateway.examples.internal.examplepb.MessageWithBody")
	proto.RegisterType((*UpdateV2Request)(nil), "grpc.gateway.examples.internal.examplepb.UpdateV2Request")
}

func init() {
	proto.RegisterFile("examples/internal/proto/examplepb/a_bit_of_everything.proto", fileDescriptor_e6ccf6cab3ab66ab)
}

var fileDescriptor_e6ccf6cab3ab66ab = []byte{
	// 3698 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x5a, 0x4b, 0x6c, 0x1b, 0x49,
	0x7a, 0x56, 0xb1, 0xa9, 0x57, 0xc9, 0x92, 0xa8, 0x92, 0x65, 0xcb, 0xb4, 0x66, 0x5c, 0xc3, 0xf1,
	0xce, 0xb6, 0xb9, 0x26, 0x5b, 0x6a, 0xc9, 0x33, 0x36, 0x67, 0x77, 0x67, 0x48, 0x49, 0xf6, 0xc8,
	0xf6, 0xc8, 0x76, 0x5b, 0xe3, 0x9d, 0xf1, 0x62, 0x56, 0x29, 0x92, 0x45, 0xb1, 0x2d, 0xf6, 0x63,
	0xbb, 0xab, 0x65, 0xd1, 0x0a, 0x91, 0x49, 0x90, 0x60, 0x83, 0x24, 0x40, 0x02, 0xe6, 0x85, 0x64,
	0x32, 0xb7, 0xe4, 0x12, 0xec, 0x21, 0x97, 0x9c, 0xf6, 0x90, 0x53, 0xb0, 0x87, 0xdc, 0x26, 0xc0,
	0x5e, 0x72, 0x0a, 0x12, 0xe4, 0x10, 0xe4, 0x16, 0x60, 0x80, 0x1c, 0x16, 0x08, 0xaa, 0xba, 0x9b,
	0xec, 0xe6, 0xc3, 0x92, 0x46, 0x5e, 0xcc, 0xfa, 0x60, 0x75, 0x55, 0xfd, 0x8f, 0xef, 0xaf, 0xfa,
	0xfb, 0x7f, 0x14, 0x1b, 0xbe, 0x4b, 0x0f, 0x89, 0x61, 0x37, 0xa8, 0xab, 0xe8, 0x26, 0xa3, 0x8e,
	0x49, 0x1a, 0x8a, 0xed, 0x58, 0xcc, 0x52, 0x82, 0x79, 0xbb, 0xac, 0x90, 0xdd, 0xb2, 0xce, 0x76,
	0xad, 0xda, 0x2e, 0x3d, 0xa0, 0x4e, 0x93, 0xd5, 0x75, 0x73, 0x2f, 0x2f, 0x68, 0x90, 0xbc, 0xe7,
	0xd8, 0x95, 0xfc, 0x1e, 0x61, 0xf4, 0x39, 0x69, 0xe6, 0x43, 0x49, 0xf9, 0x50, 0x52, 0xbe, 0x23,
	0x23, 0xbd, 0xb4, 0x67, 0x59, 0x7b, 0x0d, 0xaa, 0x10, 0x5b, 0x57, 0x88, 0x69, 0x5a, 0x8c, 0x30,
	0xdd, 0x32, 0x5d, 0x5f, 0x4e, 0x1a, 0x07, 0xab, 0x62, 0x54, 0xf6, 0x6a, 0x4a, 0x4d, 0xa7, 0x8d,
	0xea, 0xae, 0x41, 0xdc, 0xfd, 0x80, 0xe2, 0x72, 0x2f, 0x05, 0x35, 0x6c, 0xd6, 0x0c, 0x16, 0x5f,
	0xef, 0x5d, 0xac, 0x7a, 0x8e, 0x90, 0x3f, 0x6c, 0xfd, 0xb9, 0x43, 0x6c, 0x9b, 0x3a, 0xa1, 0xfa,
	0xe5, 0x61, 0x7b, 0x60, 0x13, 0x56, 0xa7, 0xa6, 0x67, 0x88, 0x87, 0x5d, 0xfe, 0x14, 0x70, 0x5c,
	0x1b, 0xc6, 0xe1, 0x7a, 0x65, 0xc5, 0xa0, 0xae, 0x4b, 0xf6, 0x68, 0x40, 0x9a, 0x7d, 0x09, 0xa9,
	0xda, 0x43, 0x7b, 0xa5, 0x17, 0x28, 0xd3, 0x0d, 0xea, 0x32, 0x62, 0xd8, 0x01, 0xc1, 0x75, 0xf1,
	0xa7, 0x92, 0xdb, 0xa3, 0x66, 0xce, 0x7d, 0x4e, 0xf6, 0xf6, 0xa8, 0xa3, 0x58, 0xb6, 0xd8, 0xca,
	0xfe, 0x6d, 0xcd, 0xfc, 0xc7, 0x12, 0x4c, 0x15, 0x4b, 0x3a, 0x7b, 0x50, 0xdb, 0xec, 0x9c, 0x1c,
	0xaa, 0xc1, 0x69, 0x57, 0x37, 0xf7, 0x1a, 0x74, 0xd7, 0xa4, 0x2e, 0xa3, 0xd5, 0xc5, 0x4b, 0x18,
	0xc8, 0x53, 0x6a, 0x31, 0x7f, 0xd2, 0xb3, 0xcc, 0xf7, 0x8a, 0xcc, 0x6f, 0x0b, 0x41, 0xda, 0x39,
	0x5f, 0xae, 0x3f, 0x42, 0x75, 0x98, 0xf4, 0x3c, 0xbd, 0xba, 0x08, 0x30, 0x90, 0x27, 0x4b, 0x3b,
	0xed, 0xe2, 0xa3, 0xcf, 0x00, 0xf8, 0x03, 0x70, 0xef, 0x87, 0x24, 0x57, 0x2b, 0xe6, 0x6e, 0x2f,
	0xe7, 0x6e, 0x7d, 0x7a, 0x74, 0xb3, 0x95, 0x8b, 0x0e, 0xd7, 0x4e, 0x33, 0x5c, 0x51, 0x5b, 0x9a,
	0xd0, 0x80, 0x3e, 0x81, 0x63, 0x81, 0x29, 0x09, 0x2c, 0xbd, 0x1a, 0x53, 0x02, 0x81, 0xe8, 0x2e,
	0x9c, 0xaa, 0x35, 0x2c, 0xc2, 0x76, 0x0f, 0x48, 0xc3, 0xa3, 0x8b, 0x12, 0x06, 0x72, 0xa2, 0x74,
	0xad, 0x5d, 0x7c, 0x4b, 0x9d, 0xbb, 0xcd, 0xe7, 0xb1, 0x98, 0xc7, 0xc2, 0x5d, 0x0b, 0xd2, 0x72,
	0x5e, 0xfd, 0x12, 0x44, 0x19, 0x34, 0x28, 0x06, 0x4f, 0xf8, 0x33, 0x7a, 0x03, 0x9e, 0xab, 0x5a,
	0x5e, 0xb9, 0x41, 0x03, 0x61, 0x49, 0x0c, 0x64, 0xa0, 0x4d, 0xf9, 0x73, 0x3e, 0xc9, 0x15, 0x38,
	0xa5, 0x9b, 0xec, 0xed, 0xb5, 0x80, 0x62, 0x14, 0x03, 0x59, 0xd2, 0xa0, 0x98, 0xea, 0xc8, 0xf0,
	0xa2, 0x14, 0x63, 0x18, 0xc8, 0x49, 0x6d, 0xca, 0x8b, 0x90, 0xf8, 0x32, 0x56, 0xd5, 0x80, 0x62,
	0x1c, 0x03, 0x79, 0x54, 0xc8, 0x58, 0x55, 0x7d, 0x82, 0x37, 0xe1, 0x74, 0x4d, 0x3f, 0xa4, 0xd5,
	0x8e, 0x90, 0x09, 0x0c, 0xe4, 0x31, 0xed, 0x5c, 0x30, 0x19, 0x27, 0xea, 0xc8, 0x99, 0xc4, 0x40,
	0x1e, 0x0f, 0x88, 0x42, 0x49, 0xaf, 0x41, 0x58, 0xb6, 0xac, 0x46, 0x40, 0x01, 0x31, 0x90, 0x27,
	0xb4, 0x49, 0x3e, 0xd3, 0x01, 0xeb, 0x32, 0x47, 0x37, 0xf7, 0x02, 0x82, 0x29, 0xee, 0x09, 0xda,
	0x94, 0x3f, 0xd7, 0x01, 0x5b, 0x6e, 0x32, 0xea, 0x06, 0x14, 0xaf, 0x61, 0x20, 0x9f, 0xd3, 0xa0,
	0x98, 0x8a, 0x19, 0xdc, 0x81, 0x31, 0x8d, 0x81, 0x3c, 0xed, 0x1b, 0x1c, 0xa2, 0xd8, 0x81, 0x90,
	0xbf, 0x99, 0x01, 0xc1, 0x0c, 0x06, 0xf2, 0x8c, 0x7a, 0xe3, 0xe4, 0x2e, 0xb0, 0xed, 0x19, 0xd4,
	0xd1, 0x2b, 0x9b, 0xa6, 0x67, 0x68, 0x93, 0x5c, 0x90, 0x2f, 0xf5, 0x13, 0x38, 0xdb, 0x79, 0xe9,
	0x03, 0xd1, 0xaf, 0x0b, 0xd1, 0x2b, 0xc7, 0x89, 0x0e, 0x83, 0x46, 0xfe, 0x21, 0x61, 0x75, 0x21,
	0x76, 0xda, 0x0e, 0x9e, 0x7c, 0xd1, 0xbf, 0x09, 0x2f, 0xf8, 0xee, 0xb5, 0xdb, 0xab, 0xe1, 0x8a,
	0xd0, 0x70, 0xe7, 0xc4, 0x1a, 0x3e, 0xf4, 0xa3, 0x47, 0xa8, 0x28, 0xf0, 0xde, 0x8e, 0xde, 0x79,
	0x33, 0x36, 0xf6, 0xb5, 0x7f, 0x0b, 0xce, 0xb8, 0xf1, 0xa3, 0x9d, 0xc5, 0x40, 0x9e, 0xd5, 0xa6,
	0xdd, 0xd8, 0xd9, 0x76, 0xc8, 0x3a, 0x6e, 0x92, 0xc2, 0x40, 0x4e, 0x85, 0x64, 0x11, 0x87, 0x74,
	0xa3, 0xe7, 0x33, 0x87, 0x81, 0x3c, 0xa7, 0x4d, 0xb9, 0x91, 0xf3, 0x09, 0x48, 0x3a, 0x72, 0x10,
	0x06, 0x32, 0xf2, 0x49, 0x42, 0x29, 0x2a, 0x5c, 0x70, 0xa8, 0x4d, 0x09, 0xdf, 0x93, 0x98, 0xcb,
	0xcc, 0x63, 0x49, 0x9e, 0xd4, 0xe6, 0xc3, 0xc5, 0xc7, 0x11, 0xd7, 0xb9, 0x05, 0xa7, 0x2c, 0x93,
	0xf2, 0xac, 0xc4, 0x33, 0xc1, 0xe2, 0x79, 0x11, 0xc5, 0x2e, 0xe4, 0xfd, 0x08, 0x9a, 0x0f, 0x23,
	0x68, 0x7e, 0x93, 0xaf, 0x7e, 0x30, 0xa2, 0x41, 0x41, 0x2c, 0x46, 0xe8, 0x4d, 0x78, 0xce, 0x67,
	0xf5, 0x75, 0x2d, 0x2e, 0x70, 0xc7, 0xfc, 0x60, 0x44, 0xf3, 0x05, 0xfa, 0x4a, 0x10, 0x85, 0x93,
	0x06, 0xb1, 0x03, 0x1c, 0x17, 0x44, 0x60, 0xf9, 0xe0, 0x0c, 0x81, 0xe5, 0x43, 0x62, 0x0b, 0xdc,
	0x9b, 0x26, 0x73, 0x9a, 0xda, 0x84, 0x11, 0x0c, 0xd1, 0x6f, 0x03, 0x38, 0x6f, 0xf0, 0x6c, 0xd4,
	0x63, 0xf9, 0x45, 0xa1, 0xf1, 0xd1, 0xd9, 0x34, 0xda, 0xb1, 0x2d, 0xf3, 0x55, 0xcf, 0x19, 0xbd,
	0xf3, 0x51, 0x0c, 0x81, 0x63, 0xfa, 0x18, 0x16, 0x5f, 0x11, 0x06, 0xdf, 0x2d, 0xfb, 0x31, 0x44,
	0xe6, 0x51, 0x01, 0x2e, 0x9a, 0x96, 0xb9, 0x6e, 0x99, 0x07, 0xd4, 0xe4, 0x39, 0x8c, 0x34, 0xb6,
	0x89, 0xe1, 0x87, 0xc5, 0xc5, 0xb4, 0x08, 0x1c, 0x43, 0xd7, 0xd1, 0x3a, 0x9c, 0xed, 0x24, 0xca,
	0x00, 0xfa, 0x65, 0xe1, 0x0e, 0xe9, 0x3e, 0x77, 0xd8, 0x09, 0xe9, 0xb4, 0x99, 0x0e, 0x8b, 0x2f,
	0x84, 0xc2, 0x8e, 0x9b, 0x45, 0x5f, 0xc9, 0x25, 0x2c, 0x7d, 0xfd, 0x78, 0x32, 0x17, 0x4a, 0xec,
	0xbe, 0x7e, 0xff, 0x08, 0xe0, 0x62, 0x5c, 0x4f, 0x37, 0x6f, 0x2f, 0xe2, 0x33, 0x28, 0x2b, 0x6d,
	0xb4, 0x8b, 0xc5, 0xec, 0x65, 0x2d, 0x90, 0x8d, 0x4d, 0x7f, 0x09, 0x73, 0x1d, 0x98, 0xe9, 0xac,
	0x41, 0xd5, 0xcc, 0xe0, 0xc5, 0x2a, 0x75, 0x2b, 0x8e, 0x2e, 0xaa, 0x88, 0xbc, 0x76, 0x21, 0x0a,
	0xb9, 0xd8, 0x81, 0x86, 0xbe, 0x00, 0x70, 0xa1, 0xbb, 0x2d, 0x51, 0xd0, 0x6f, 0x9c, 0x21, 0xe2,
	0x96, 0xd4, 0x76, 0x51, 0xc9, 0xa2, 0xed, 0x7e, 0xac, 0x97, 0xb6, 0x87, 0x42, 0x9c, 0xef, 0x44,
	0xe9, 0x08, 0xbe, 0x03, 0x98, 0xee, 0x0d, 0x21, 0x11, 0x8c, 0x19, 0x1e, 0x47, 0x4a, 0x37, 0xdb,
	0xc5, 0x1b, 0xd9, 0x85, 0xce, 0x26, 0xf8, 0x64, 0x81, 0xbe, 0xa5, 0xde, 0xe9, 0x98, 0xca, 0xc5,
	0x78, 0x04, 0x8a, 0xe8, 0xfd, 0x39, 0x88, 0x28, 0x0e, 0xde, 0x9e, 0x88, 0xe2, 0x37, 0x5f, 0x51,
	0x45, 0x52, 0xba, 0xdd, 0x2e, 0xae, 0x67, 0xbb, 0x20, 0x7d, 0x4d, 0xd8, 0x2a, 0x3f, 0xa3, 0x15,
	0x16, 0x98, 0xf0, 0xe6, 0x90, 0xd5, 0xc1, 0x96, 0xf8, 0x72, 0x23, 0x96, 0xfc, 0x2d, 0x80, 0x73,
	0xfd, 0x06, 0x5c, 0x7d, 0x45, 0xd5, 0x61, 0x69, 0xad, 0x5d, 0x5c, 0xc9, 0xce, 0x6f, 0x0f, 0xc0,
	0x9d, 0xde, 0x1e, 0x0e, 0x37, 0x65, 0xf6, 0xc2, 0x7c, 0x07, 0xce, 0xfb, 0xd9, 0xc4, 0x3a, 0xa0,
	0x8e, 0xa3, 0x57, 0xe9, 0x2e, 0x6b, 0xda, 0x74, 0xf1, 0x5b, 0xbc, 0x56, 0x2a, 0x8d, 0xb7, 0x8b,
	0xc9, 0xbf, 0x4e, 0x00, 0x49, 0x9b, 0x13, 0x34, 0x0f, 0x02, 0x92, 0x9d, 0xa6, 0x4d, 0xd3, 0xff,
	0x05, 0xe0, 0x58, 0x50, 0x9b, 0x22, 0x98, 0x34, 0x89, 0x41, 0xfd, 0xda, 0x54, 0x13, 0xcf, 0xe8,
	0x02, 0x1c, 0x23, 0x86, 0xe5, 0x99, 0x6c, 0x31, 0x21, 0x6a, 0x8c, 0x60, 0x84, 0x0e, 0x60, 0xc2,
	0xda, 0x17, 0x95, 0xdf, 0x8c, 0x7a, 0xf7, 0xcc, 0xdb, 0x90, 0xdf, 0xa0, 0xd4, 0x16, 0x9e, 0x9f,
	0x6e, 0x17, 0x2f, 0xaa, 0x0b, 0xe1, 0x30, 0x6e, 0x75, 0xc2, 0xda, 0xcf, 0x5c, 0x81, 0x13, 0xe1,
	0x22, 0x9a, 0x84, 0xa3, 0xb7, 0x8b, 0xf7, 0x1f, 0x6f, 0xa6, 0x46, 0xd0, 0x04, 0x4c, 0xee, 0x68,
	0x1f, 0x6d, 0xa6, 0x40, 0xe1, 0x62, 0xbb, 0x78, 0x5e, 0x45, 0x28, 0x75, 0x84, 0x33, 0xd6, 0x7e,
	0xa6, 0x80, 0x33, 0x7c, 0x3e, 0x83, 0x5b, 0x69, 0x07, 0x4e, 0xc7, 0xb2, 0x0d, 0x4a, 0x41, 0x69,
	0x9f, 0x36, 0x03, 0x6b, 0xf9, 0x23, 0xba, 0x07, 0x47, 0xfd, 0xf0, 0x96, 0x38, 0x4b, 0xb9, 0xe4,
	0xcb, 0x28, 0x24, 0x6e, 0x82, 0xf4, 0x06, 0xbc, 0x30, 0x38, 0xdf, 0x0c, 0x50, 0x7e, 0x3e, 0xaa,
	0x7c, 0x32, 0x2a, 0xe5, 0x27, 0x20, 0x14, 0xd3, 0x9b, 0x32, 0x06, 0x88, 0xf9, 0x41, 0x54, 0xcc,
	0x2b, 0xa9, 0xfa, 0xbb, 0x48, 0x0a, 0x7f, 0x95, 0x68, 0x17, 0xff, 0x3c, 0x01, 0x7f, 0x17, 0x64,
	0xe7, 0x8b, 0xb8, 0xac, 0x33, 0x6c, 0xd5, 0x70, 0xb7, 0xfd, 0x55, 0xb7, 0xb6, 0x4c, 0x16, 0xe6,
	0xa1, 0x26, 0xae, 0x58, 0x86, 0xdd, 0xd0, 0x2b, 0xe2, 0xd5, 0x0b, 0x1a, 0x3a, 0xcc, 0x9d, 0x12,
	0x33, 0x0b, 0x57, 0xb8, 0x9b, 0x62, 0x83, 0x98, 0x4d, 0x5c, 0xa3, 0x84, 0x79, 0x0e, 0x75, 0xb9,
	0xac, 0x87, 0x61, 0x42, 0xfa, 0x12, 0x88, 0x26, 0xe6, 0x4b, 0x10, 0xad, 0xfc, 0xbf, 0x04, 0xb1,
	0x56, 0x21, 0xfb, 0x04, 0x5e, 0xbd, 0xad, 0x9b, 0x55, 0x6c, 0x79, 0x0c, 0x1b, 0x96, 0x43, 0x31,
	0x29, 0xf3, 0xc7, 0xbe, 0xde, 0x2e, 0x5f, 0x67, 0xcc, 0x76, 0x0b, 0x8a, 0xb2, 0xa7, 0xb3, 0xba,
	0x57, 0xce, 0x57, 0x2c, 0x43, 0xe1, 0xbb, 0x92, 0xa3, 0x15, 0xcb, 0x6d, 0xba, 0x8c, 0x06, 0xc3,
	0x60, 0x93, 0xd4, 0x35, 0xa4, 0x1e, 0xe1, 0x0c, 0xd7, 0xcf, 0xfd, 0x67, 0xb9, 0x52, 0x5b, 0x7d,
	0x7b, 0x85, 0xae, 0xe4, 0xd6, 0xca, 0x6b, 0x6b, 0xb9, 0xb5, 0x9b, 0xab, 0xd5, 0x1c, 0x59, 0xb9,
	0x71, 0x2b, 0x77, 0x63, 0xad, 0x4a, 0xca, 0xd5, 0xda, 0x3b, 0xf4, 0xe6, 0xca, 0x5a, 0x06, 0xb7,
	0x4a, 0xd3, 0x61, 0xe5, 0x25, 0xc0, 0x65, 0x7e, 0x32, 0x09, 0x17, 0x7b, 0x91, 0x84, 0x91, 0x08,
	0xdd, 0x82, 0x97, 0x44, 0x91, 0xdb, 0x09, 0x91, 0xd1, 0x76, 0x0a, 0x60, 0x49, 0x4e, 0x68, 0x17,
	0x38, 0x41, 0xc8, 0x70, 0xbb, 0xdb, 0x2f, 0xbd, 0x0b, 0xd3, 0x71, 0xd6, 0x58, 0xf7, 0xc4, 0x5b,
	0x3d, 0xa0, 0x5d, 0x8c, 0xf2, 0x6e, 0x44, 0x3a, 0xa9, 0x3e, 0xbd, 0xd1, 0x0a, 0x54, 0xc2, 0x92,
	0x2c, 0xc5, 0xf5, 0x6e, 0x75, 0x8b, 0xd1, 0x3e, 0xbd, 0xb1, 0x8e, 0x2b, 0x89, 0x25, 0x39, 0x19,
	0xd7, 0xfb, 0x51, 0xa4, 0x92, 0x1d, 0xa4, 0xb7, 0x53, 0x1c, 0x8f, 0x62, 0x49, 0x1e, 0xed, 0xd3,
	0x1b, 0xd6, 0xc9, 0xdf, 0x83, 0x97, 0x7b, 0xb6, 0x2a, 0x56, 0x7e, 0x8f, 0x61, 0x49, 0x1e, 0xd3,
	0x16, 0x63, 0x9b, 0x15, 0xad, 0xc4, 0x07, 0xb3, 0x47, 0xfa, 0x40, 0x49, 0x1e, 0x1f, 0xc0, 0x1e,
	0x6a, 0x7f, 0x07, 0x2e, 0xc6, 0xd9, 0x23, 0x9d, 0xdd, 0x04, 0x96, 0xe4, 0x09, 0x6d, 0x21, 0xca,
	0x5b, 0xea, 0x74, 0x79, 0x7d, 0xdb, 0x15, 0x2b, 0x63, 0x27, 0x45, 0x01, 0x1f, 0xdb, 0xae, 0x78,
	0x11, 0xdf, 0xb3, 0x5d, 0xd1, 0x6e, 0x10, 0x62, 0x49, 0x3e, 0x17, 0xdf, 0xae, 0x52, 0xb7, 0x33,
	0x1c, 0x78, 0x4c, 0x1d, 0x73, 0xa7, 0xb0, 0x24, 0x4f, 0xf7, 0x1f, 0x53, 0x68, 0xad, 0xd9, 0x6b,
	0x6d, 0xa4, 0xe2, 0x3b, 0x77, 0x96, 0x8a, 0x2f, 0xb6, 0x49, 0xdd, 0xaa, 0xef, 0x3d, 0xb8, 0xd4,
	0xb3, 0x49, 0xf1, 0xd3, 0x99, 0xc6, 0x92, 0x3c, 0xab, 0x5d, 0x8a, 0x6d, 0x53, 0xac, 0x1d, 0x1b,
	0x22, 0xa0, 0xe3, 0x1d, 0x33, 0x58, 0x92, 0x53, 0x83, 0x04, 0x0c, 0xf5, 0xea, 0x58, 0xdb, 0x36,
	0x8b, 0x25, 0x79, 0xae, 0xe7, 0x98, 0x22, 0xdb, 0x35, 0x90, 0x39, 0xd2, 0x18, 0x4a, 0x32, 0xea,
	0x67, 0x0e, 0x34, 0x17, 0xea, 0xed, 0x22, 0x55, 0x2b, 0x88, 0x1c, 0xe1, 0xcc, 0x30, 0x0f, 0xcb,
	0x14, 0xf0, 0x0f, 0x99, 0xe3, 0xd1, 0xeb, 0xd8, 0xff, 0xbf, 0x46, 0x1a, 0x6e, 0x30, 0xf8, 0xf4,
	0x7a, 0x2f, 0x5b, 0x04, 0x37, 0xe7, 0x5b, 0xb9, 0x8e, 0xd5, 0xeb, 0x78, 0xf5, 0x53, 0xdc, 0xca,
	0xa4, 0x61, 0xb2, 0x64, 0x55, 0x9b, 0x83, 0xd2, 0x7b, 0x86, 0xc2, 0xd9, 0xa0, 0x5b, 0xfe, 0x81,
	0xce, 0xea, 0x82, 0x6c, 0x06, 0x26, 0xc2, 0xfb, 0x29, 0x2d, 0xa1, 0x57, 0x51, 0x09, 0x26, 0xab,
	0x84, 0x91, 0x20, 0x9f, 0xe4, 0x4f, 0xee, 0x00, 0x5c, 0x9a, 0x26, 0x78, 0x33, 0x7f, 0x03, 0xe0,
	0xec, 0x47, 0x76, 0x95, 0x30, 0xfa, 0x44, 0xd5, 0xe8, 0x8f, 0x3d, 0xea, 0x32, 0x74, 0x1f, 0x4a,
	0xa4, 0xec, 0xa3, 0x99, 0x52, 0x0b, 0x5f, 0x3f, 0x4d, 0x69, 0x5c, 0x0c, 0x7a, 0x17, 0x4e, 0x79,
	0x42, 0x81, 0xb8, 0x1e, 0x0d, 0xc0, 0xf6, 0x37, 0x3a, 0xb7, 0x75, 0xda, 0xa8, 0x7e, 0x48, 0xdc,
	0x7d, 0x0d, 0xfa, 0xe4, 0xfc, 0x39, 0x8b, 0xe1, 0x54, 0xc4, 0x5b, 0x79, 0x31, 0xf1, 0x74, 0x53,
	0x7b, 0x90, 0x1a, 0x41, 0xe3, 0x50, 0x7a, 0xb0, 0xbd, 0x99, 0x02, 0xea, 0xbf, 0xbd, 0x05, 0x2f,
	0xf6, 0x2a, 0x7e, 0x4c, 0x9d, 0x03, 0xbd, 0x42, 0xd1, 0x67, 0x49, 0x38, 0xb6, 0xee, 0xf0, 0x53,
	0x40, 0x67, 0x30, 0x23, 0x7d, 0x06, 0xde, 0xcc, 0x2f, 0x13, 0xbf, 0xf3, 0xaf, 0xff, 0xf9, 0xa7,
	0x89, 0xaf, 0x12, 0x99, 0xff, 0x4d, 0x28, 0x07, 0x2b, 0xe1, 0x2d, 0xf5, 0xa0, 0x3b, 0x6a, 0xe5,
	0x28, 0x92, 0x6b, 0x5a, 0xca, 0x51, 0x34, 0x7d, 0xb4, 0x94, 0xa3, 0x88, 0x07, 0xb7, 0x14, 0x97,
	0xda, 0xc4, 0x21, 0xcc, 0x72, 0x94, 0x23, 0x2f, 0xb6, 0x70, 0x14, 0xf1, 0xb6, 0x96, 0x72, 0x14,
	0x7b, 0xe9, 0xc2, 0x71, 0x64, 0xbd, 0xeb, 0xd2, 0x2d, 0xe5, 0x28, 0x1a, 0x08, 0xbf, 0xe7, 0x32,
	0xc7, 0x76, 0x68, 0x4d, 0x3f, 0x54, 0xb2, 0x2d, 0x5f, 0x49, 0x84, 0xcd, 0xed, 0x95, 0xe3, 0xf6,
	0x2a, 0x72, 0x7b, 0x18, 0xe2, 0x20, 0x87, 0x75, 0xc6, 0x2d, 0xe5, 0xa8, 0x1b, 0xd8, 0x5a, 0xca,
	0x51, 0xcf, 0x7d, 0x13, 0xe7, 0x1c, 0x78, 0x11, 0x15, 0xe3, 0x8b, 0x74, 0x03, 0x2d, 0xf4, 0x0f,
	0x00, 0x42, 0xdf, 0x05, 0xc4, 0x2b, 0xf4, 0x4d, 0xb9, 0x41, 0x56, 0x78, 0xc1, 0xd5, 0xcc, 0x95,
	0x63, 0x7c, 0xa0, 0x00, 0xb2, 0xe8, 0xf7, 0x00, 0x1c, 0xbb, 0x6f, 0x59, 0xfb, 0x9e, 0x8d, 0x66,
	0xf3, 0xae, 0x57, 0x56, 0xf3, 0x5b, 0xd5, 0x20, 0x14, 0x9c, 0x09, 0x43, 0x5e, 0x60, 0x90, 0xd1,
	0x5b, 0xc7, 0xfa, 0x21, 0x2f, 0xb0, 0x5a, 0xe8, 0x8f, 0x01, 0x1c, 0xf3, 0x43, 0xc3, 0x99, 0xb6,
	0x6d, 0xc8, 0x15, 0x57, 0x66, 0x45, 0xc0, 0xf9, 0x4e, 0xfa, 0x84, 0x70, 0xf8, 0xce, 0xfc, 0x12,
	0xc0, 0x89, 0x30, 0x58, 0xa1, 0x5b, 0x27, 0xc7, 0xd4, 0x13, 0xe0, 0x86, 0x42, 0xfa, 0x02, 0x08,
	0x4c, 0x7f, 0x01, 0xd2, 0x59, 0xe5, 0x40, 0x7d, 0x39, 0x28, 0x52, 0xa6, 0x79, 0x1f, 0x18, 0x8f,
	0x72, 0x4f, 0x57, 0xd4, 0x53, 0xb3, 0x2c, 0xab, 0xdf, 0x51, 0x0e, 0x54, 0x72, 0x52, 0x1e, 0x90,
	0x45, 0x7f, 0x07, 0xe0, 0xd8, 0x06, 0x6d, 0x50, 0x46, 0xfb, 0x3d, 0x63, 0x98, 0x4d, 0x4e, 0xbb,
	0x58, 0x2c, 0x5f, 0x83, 0x33, 0x10, 0x16, 0x6d, 0xfd, 0x1e, 0x6d, 0x16, 0x3d, 0x56, 0x47, 0x23,
	0xf0, 0x22, 0x1c, 0x7b, 0xc0, 0x1f, 0x55, 0x34, 0x0d, 0x93, 0x0e, 0x25, 0x55, 0x38, 0xfa, 0xdc,
	0xd1, 0x19, 0x7d, 0x76, 0x1e, 0xce, 0x1c, 0xe6, 0x74, 0xc7, 0xe1, 0x20, 0x5c, 0xbd, 0xdc, 0xa0,
	0x28, 0x81, 0xfd, 0x6d, 0x91, 0xb3, 0x27, 0xf5, 0x9c, 0xff, 0x01, 0x70, 0xe2, 0x0e, 0x65, 0x8f,
	0x3c, 0xea, 0x34, 0x7f, 0x25, 0xbe, 0xf3, 0x87, 0xa0, 0x5d, 0xdc, 0xc9, 0x6c, 0xc3, 0xa5, 0x41,
	0x5d, 0x46, 0x47, 0xf3, 0x29, 0xbb, 0x8b, 0x8f, 0x41, 0x79, 0x44, 0x18, 0x9a, 0x47, 0xd7, 0x8f,
	0x33, 0xf4, 0xc7, 0x5c, 0x41, 0x68, 0xee, 0x17, 0xa3, 0x30, 0x75, 0x87, 0xb2, 0xb0, 0x96, 0xf0,
	0x95, 0x97, 0xce, 0x90, 0x37, 0x03, 0x41, 0xe9, 0x57, 0x20, 0x23, 0xf3, 0x59, 0x52, 0xd8, 0xf4,
	0x7f, 0x12, 0xfa, 0x4a, 0x3a, 0xc6, 0xaa, 0x4e, 0xc9, 0x12, 0x04, 0xde, 0x41, 0x3d, 0x50, 0xab,
	0x77, 0xad, 0x27, 0x4b, 0x0d, 0x6d, 0x62, 0xfa, 0xd6, 0xbc, 0x97, 0x2d, 0xc6, 0xb3, 0xc7, 0x4b,
	0xda, 0x8c, 0xc1, 0xab, 0x43, 0x79, 0x63, 0xf9, 0x6e, 0x78, 0x1b, 0xd0, 0xcf, 0xd7, 0x2d, 0xf3,
	0x07, 0x1a, 0x32, 0x54, 0x61, 0x7f, 0x3a, 0x1b, 0x52, 0x52, 0x0f, 0x59, 0x1e, 0x6a, 0xa7, 0xfb,
	0x32, 0xad, 0xb1, 0x74, 0x8b, 0x3e, 0x4f, 0xc2, 0xe4, 0x66, 0xa5, 0x6e, 0xa1, 0x63, 0x7f, 0x0a,
	0x72, 0xbd, 0x72, 0xde, 0x6f, 0x77, 0xc2, 0xb0, 0x72, 0x7a, 0x96, 0xcc, 0x4f, 0xa5, 0x76, 0xf1,
	0x9f, 0x13, 0x70, 0x82, 0x56, 0xea, 0x16, 0x76, 0xec, 0x0a, 0x9a, 0x7b, 0xec, 0x19, 0x06, 0x71,
	0x9a, 0x05, 0xbc, 0x19, 0x4c, 0xa5, 0x53, 0x1b, 0xdd, 0xeb, 0x23, 0x31, 0x9b, 0xd9, 0x80, 0x28,
	0xfe, 0x32, 0x0b, 0xc4, 0xa7, 0x7c, 0x85, 0xef, 0xde, 0x82, 0x92, 0xba, 0xbc, 0x8c, 0xd4, 0xcc,
	0x32, 0x4c, 0x11, 0xdb, 0xbf, 0xe4, 0xd0, 0x2d, 0x53, 0x79, 0xe6, 0x5a, 0x26, 0x5a, 0x3a, 0xca,
	0x84, 0x55, 0x78, 0x86, 0xd5, 0x29, 0xd6, 0x4d, 0xdb, 0x0b, 0x7e, 0x11, 0xcd, 0xb4, 0xee, 0x3e,
	0x81, 0xd2, 0x8d, 0xe5, 0x55, 0xf4, 0x00, 0xbe, 0xad, 0x51, 0xe6, 0x39, 0x26, 0xad, 0xe2, 0xe7,
	0x75, 0x6a, 0x62, 0x4e, 0xe9, 0x50, 0xd7, 0xf2, 0x9c, 0x0a, 0xc5, 0xba, 0x8b, 0x19, 0x35, 0x6c,
	0xcb, 0x21, 0x8e, 0xde, 0x68, 0x62, 0xcf, 0x24, 0x07, 0x44, 0x6f, 0x90, 0x72, 0x83, 0xe6, 0xb3,
	0x0b, 0x70, 0xe2, 0x30, 0x67, 0x7a, 0x46, 0x99, 0x3a, 0x68, 0x72, 0x6e, 0x44, 0xfc, 0xfb, 0xe4,
	0xfd, 0xbb, 0xef, 0x42, 0x69, 0x6d, 0x79, 0x0d, 0xad, 0xc1, 0xec, 0x4b, 0xe4, 0x56, 0x2d, 0xea,
	0x62, 0xd3, 0x62, 0x98, 0x1e, 0xea, 0x2e, 0xcb, 0xa3, 0x31, 0x28, 0xae, 0x05, 0xc5, 0xab, 0xfb,
	0xe9, 0xf1, 0xe1, 0x88, 0x6f, 0xb5, 0x72, 0xe4, 0x1f, 0xf7, 0xd3, 0x4b, 0x99, 0x54, 0x34, 0x15,
	0xf1, 0xb5, 0x82, 0x7f, 0x53, 0xf4, 0x14, 0xa1, 0xbe, 0x25, 0xf4, 0x73, 0x00, 0xcf, 0x6d, 0x50,
	0x6a, 0x8b, 0x5f, 0xdd, 0xf8, 0xc4, 0x37, 0x55, 0x23, 0xbd, 0x27, 0xac, 0xbd, 0x95, 0x59, 0x3b,
	0x36, 0xcb, 0xc4, 0xbe, 0x07, 0xc8, 0xf3, 0x76, 0x49, 0xa4, 0xc7, 0x22, 0x84, 0xdb, 0x56, 0x49,
	0x37, 0xab, 0xba, 0xb9, 0xe7, 0xa2, 0x4b, 0x7d, 0xb9, 0x63, 0x23, 0xf8, 0xca, 0x62, 0x68, 0x5a,
	0x19, 0x41, 0x4f, 0xe0, 0xf8, 0x8e, 0x6e, 0x50, 0xcb, 0x63, 0x68, 0x08, 0xd1, 0x50, 0xe6, 0xcb,
	0x02, 0xfe, 0x02, 0x9a, 0x8f, 0xee, 0x30, 0x0b, 0x84, 0xd5, 0x61, 0x6a, 0xd3, 0x71, 0x2c, 0x87,
	0xf7, 0x72, 0x1b, 0x94, 0x11, 0xbd, 0xe1, 0x9e, 0x5a, 0xc1, 0x55, 0xa1, 0xe0, 0x75, 0xb4, 0x14,
	0x3b, 0x42, 0x2e, 0xf5, 0xb9, 0xce, 0xea, 0xd5, 0x40, 0xea, 0x9f, 0x00, 0x88, 0xee, 0x50, 0xd6,
	0xdb, 0x3b, 0x9e, 0xa2, 0x5a, 0xea, 0x61, 0x1d, 0x8a, 0xe7, 0xdb, 0x02, 0xcf, 0x1b, 0x99, 0x4b,
	0x51, 0x3c, 0x1c, 0x4a, 0xd9, 0xaa, 0x36, 0x95, 0x23, 0x5e, 0xb3, 0x88, 0x1e, 0x13, 0xfd, 0x11,
	0x80, 0x73, 0x0f, 0x2d, 0x97, 0x71, 0x89, 0x82, 0x55, 0x20, 0x3a, 0x65, 0xbf, 0x3a, 0x14, 0x86,
	0x22, 0x60, 0x5c, 0xcb, 0x5c, 0x8d, 0xc2, 0xb0, 0x2d, 0x97, 0x71, 0x28, 0xe2, 0xb7, 0x56, 0x1f,
	0x4f, 0xc7, 0x4d, 0x7e, 0x01, 0xe0, 0xfc, 0x7a, 0x9d, 0x56, 0xf6, 0xc3, 0x42, 0xe1, 0x21, 0x71,
	0x88, 0xe1, 0x7e, 0x63, 0x7e, 0x7f, 0x47, 0x18, 0x50, 0x44, 0xef, 0x1d, 0xe7, 0xf7, 0xb6, 0xc0,
	0xa9, 0xec, 0x51, 0x36, 0xf0, 0x15, 0x40, 0xff, 0x0d, 0xe0, 0x6b, 0xc2, 0x30, 0xff, 0x7a, 0x98,
	0x77, 0xcc, 0xbf, 0x26, 0x26, 0x3e, 0x12, 0x26, 0xde, 0x43, 0x5b, 0xa7, 0x30, 0x31, 0xe8, 0xf4,
	0xc4, 0xe7, 0x4c, 0x3d, 0xe6, 0x5a, 0xfb, 0x2d, 0xf4, 0xef, 0x00, 0x9e, 0x17, 0xc6, 0x72, 0xcf,
	0xfa, 0x35, 0xb2, 0x31, 0x53, 0x38, 0xa1, 0x8d, 0xdc, 0x45, 0xe3, 0x3d, 0x77, 0xab, 0x10, 0xff,
	0xd2, 0x09, 0x7d, 0x0e, 0xe0, 0xd2, 0x83, 0x03, 0xea, 0x88, 0xca, 0x5c, 0xa3, 0xae, 0x6d, 0x99,
	0x2e, 0x5d, 0xb7, 0xc4, 0x55, 0xfe, 0x4e, 0xd3, 0xa6, 0x43, 0x43, 0xc8, 0x52, 0xdf, 0x7c, 0xe4,
	0x12, 0x33, 0xb3, 0xd9, 0x2e, 0xa2, 0x42, 0x2c, 0x3d, 0x32, 0x7a, 0xc8, 0x04, 0xfc, 0x2c, 0x92,
	0xa3, 0xaf, 0x91, 0x15, 0x2a, 0x77, 0x02, 0xe5, 0x15, 0x5f, 0x39, 0xe3, 0xca, 0x7f, 0x1f, 0xc0,
	0x05, 0x71, 0x02, 0x9b, 0x87, 0xfe, 0xee, 0x84, 0xdf, 0x6d, 0xa0, 0xef, 0x9e, 0xf6, 0x83, 0x10,
	0x1e, 0x19, 0x42, 0xee, 0xa1, 0x2f, 0xfa, 0x25, 0x81, 0x70, 0x1e, 0xcd, 0x71, 0x84, 0x41, 0xb2,
	0x2b, 0x54, 0x38, 0x00, 0xf4, 0x67, 0x00, 0x5e, 0x8e, 0x41, 0x89, 0x7f, 0x58, 0x72, 0x7c, 0x31,
	0x3e, 0x08, 0x50, 0x5c, 0xc6, 0xd7, 0x80, 0x95, 0xfe, 0x27, 0xd0, 0x2e, 0xfe, 0x0c, 0xa0, 0xda,
	0x90, 0xfb, 0xa9, 0xe8, 0x6f, 0x68, 0x38, 0x97, 0xc3, 0xcf, 0xeb, 0x7a, 0xa5, 0x8e, 0xdd, 0xba,
	0xe5, 0x35, 0xaa, 0xa2, 0x18, 0x28, 0x53, 0xec, 0xb9, 0xb4, 0x8a, 0x75, 0x13, 0xdb, 0x0d, 0x52,
	0xa1, 0xd8, 0xaa, 0x89, 0xb2, 0xa1, 0x6a, 0x55, 0x3c, 0x83, 0x9a, 0xfe, 0x1d, 0x07, 0xae, 0x58,
	0x06, 0x1f, 0xbc, 0x91, 0x7e, 0x04, 0xaf, 0x0c, 0xea, 0x87, 0x78, 0x52, 0x0f, 0x6f, 0xc4, 0x4e,
	0xfb, 0x83, 0xcb, 0x33, 0x78, 0xbe, 0x42, 0x0c, 0xda, 0x58, 0x27, 0x2e, 0x0d, 0x64, 0x6c, 0x13,
	0x83, 0x22, 0x0d, 0x8e, 0xfa, 0x9f, 0xa6, 0x9c, 0x36, 0x89, 0xc5, 0x76, 0xab, 0x93, 0xc4, 0xf8,
	0x92, 0xfa, 0x23, 0xb8, 0x54, 0x34, 0x2d, 0x56, 0xa7, 0x4e, 0xa0, 0x49, 0x1c, 0x42, 0x37, 0xa1,
	0x7f, 0x3f, 0x96, 0xde, 0x4f, 0xab, 0x78, 0xa4, 0xf4, 0xb3, 0xc9, 0x76, 0xf1, 0xa7, 0x93, 0xe8,
	0x2b, 0x00, 0xe7, 0x8b, 0xb8, 0xe4, 0xff, 0x44, 0x16, 0x79, 0x7f, 0x3f, 0x86, 0xe7, 0xf7, 0xb4,
	0x87, 0xeb, 0xb9, 0x3b, 0xbe, 0xe9, 0xd8, 0x76, 0xac, 0x67, 0xb4, 0xc2, 0x4e, 0xbb, 0x65, 0xe9,
	0x94, 0x69, 0x99, 0xf4, 0xfd, 0xc0, 0x34, 0x4e, 0x9d, 0xfd, 0x11, 0x3c, 0x5f, 0x7a, 0xbc, 0x81,
	0x57, 0x73, 0xeb, 0x0d, 0xe2, 0xb9, 0x14, 0xdf, 0xd7, 0x2b, 0xd4, 0x74, 0x29, 0xba, 0x7d, 0x3a,
	0xc9, 0x4a, 0xb9, 0x61, 0x95, 0x15, 0x83, 0xb8, 0x8c, 0x3a, 0xca, 0xfd, 0xad, 0xf5, 0xcd, 0xed,
	0xc7, 0x9b, 0x79, 0x76, 0xc8, 0x54, 0x69, 0x25, 0xbf, 0x5c, 0xc0, 0x70, 0xe1, 0x30, 0xe7, 0x5a,
	0x06, 0x15, 0xd6, 0x74, 0x9f, 0xd0, 0x78, 0x7a, 0xb4, 0x49, 0xaa, 0x55, 0x92, 0x95, 0x40, 0x22,
	0xa9, 0xf6, 0x55, 0xc5, 0xea, 0x85, 0xe8, 0xcc, 0x61, 0xae, 0x66, 0x59, 0x39, 0x43, 0x37, 0x68,
	0xa1, 0x8f, 0xb2, 0x30, 0x84, 0x52, 0x7b, 0xc8, 0x2b, 0xdc, 0x55, 0xb4, 0x05, 0xef, 0xf4, 0x57,
	0xb8, 0x9e, 0x4b, 0x9d, 0x6e, 0x75, 0x5b, 0x27, 0x07, 0x14, 0xdb, 0xd4, 0x31, 0x74, 0xd7, 0xe5,
	0xae, 0xcb, 0x2c, 0x4c, 0x2a, 0x15, 0xea, 0xba, 0xb1, 0x6a, 0x38, 0xaf, 0x9d, 0xa1, 0x66, 0x1e,
	0xd7, 0x1e, 0x41, 0x69, 0x6d, 0xe5, 0x26, 0xba, 0x0b, 0xa7, 0xb7, 0xbe, 0x6d, 0x60, 0x82, 0x19,
	0x25, 0xb6, 0xc5, 0xf2, 0xe8, 0x16, 0x7c, 0x27, 0xfd, 0xf5, 0x7e, 0x25, 0x79, 0xfa, 0x97, 0x12,
	0x9c, 0x85, 0x93, 0x25, 0xe2, 0xea, 0x15, 0x71, 0x7f, 0x92, 0x98, 0x00, 0xf0, 0xef, 0x41, 0xec,
	0x4a, 0xe5, 0x73, 0x30, 0x91, 0x48, 0x4f, 0x7e, 0x9c, 0x2b, 0x3e, 0xdc, 0xca, 0xdd, 0xa3, 0x4d,
	0x9c, 0xb8, 0x2b, 0xc3, 0xa5, 0xc3, 0x1c, 0x31, 0xc8, 0x0b, 0xcb, 0xcc, 0x11, 0x5b, 0x0f, 0x74,
	0xe6, 0x88, 0xc7, 0xea, 0x22, 0x7e, 0x4e, 0xa4, 0xc7, 0x2c, 0x3e, 0x50, 0xef, 0xfe, 0x06, 0x7c,
	0x7d, 0x18, 0xa5, 0xe5, 0xe8, 0x2f, 0xa8, 0x83, 0xbe, 0x9f, 0xfd, 0x2e, 0x9c, 0x85, 0x49, 0xc1,
	0x37, 0x9e, 0x1e, 0x65, 0xd6, 0x3e, 0x35, 0xe1, 0x35, 0xb8, 0xd4, 0x25, 0xd1, 0xa8, 0xeb, 0x35,
	0xd8, 0x0e, 0x6b, 0x6c, 0x99, 0x8f, 0x79, 0x98, 0xae, 0xba, 0x9d, 0x26, 0x64, 0xfb, 0x7d, 0xf8,
	0x0b, 0xd0, 0xb9, 0xef, 0xf9, 0x17, 0x30, 0x21, 0xc9, 0x49, 0xf5, 0xcd, 0xd0, 0xf9, 0x22, 0x9e,
	0xaa, 0x08, 0x3c, 0x4a, 0x47, 0x68, 0xe1, 0xca, 0x70, 0x22, 0x01, 0xa1, 0xf4, 0x5b, 0x30, 0xed,
	0x5f, 0x1f, 0x21, 0x74, 0xc7, 0x21, 0x26, 0x73, 0x31, 0x1f, 0x04, 0x87, 0x0a, 0x97, 0x82, 0x4b,
	0x25, 0x34, 0x1f, 0x2c, 0x8a, 0x51, 0xb8, 0xba, 0x0e, 0x47, 0x49, 0xd5, 0xd0, 0x4d, 0x54, 0x88,
	0xb1, 0x9a, 0xd5, 0x18, 0x99, 0xf0, 0x11, 0x4e, 0xa6, 0xbb, 0x8c, 0x97, 0xef, 0x07, 0xbc, 0x6f,
	0xab, 0x59, 0x8e, 0x21, 0xdc, 0xb0, 0x7c, 0x05, 0x4e, 0x47, 0x0f, 0x66, 0xa4, 0xf7, 0xa2, 0xab,
	0x7c, 0x6d, 0xe8, 0x55, 0x57, 0x2f, 0xa9, 0xb3, 0x05, 0x2f, 0x7e, 0xd8, 0x0d, 0x9b, 0xd1, 0x60,
	0x70, 0xda, 0x20, 0xf0, 0xe2, 0x32, 0x44, 0x87, 0xb9, 0xe8, 0x0c, 0x7f, 0x5b, 0xd0, 0x68, 0x5a,
	0x2a, 0x13, 0xe7, 0x85, 0x0c, 0x2f, 0xf6, 0x2c, 0x96, 0xc9, 0x8b, 0x5c, 0x43, 0x77, 0x19, 0x9a,
	0x56, 0xa7, 0xe0, 0x68, 0x5a, 0xb2, 0x4c, 0x0a, 0x13, 0x18, 0x3c, 0x9d, 0xec, 0xb8, 0x63, 0x79,
	0x4c, 0xc4, 0xb3, 0xd5, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x52, 0x68, 0xc9, 0xfa, 0x00, 0x2f,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ABitOfEverythingServiceClient is the client API for ABitOfEverythingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ABitOfEverythingServiceClient interface {
	// Create a new ABitOfEverything
	//
	// This API creates a new ABitOfEverything
	Create(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	CreateBody(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	Lookup(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*ABitOfEverything, error)
	Update(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateV2(ctx context.Context, in *UpdateV2Request, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	GetQuery(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*empty.Empty, error)
	GetRepeatedQuery(ctx context.Context, in *ABitOfEverythingRepeated, opts ...grpc.CallOption) (*ABitOfEverythingRepeated, error)
	// Echo allows posting a StringMessage value.
	//
	// It also exposes multiple bindings.
	//
	// This makes it useful when validating that the OpenAPI v2 API
	// description exposes documentation correctly on all paths
	// defined as additional_bindings in the proto.
	Echo(ctx context.Context, in *sub.StringMessage, opts ...grpc.CallOption) (*sub.StringMessage, error)
	DeepPathEcho(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	NoBindings(ctx context.Context, in *duration.Duration, opts ...grpc.CallOption) (*empty.Empty, error)
	Timeout(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	ErrorWithDetails(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GetMessageWithBody(ctx context.Context, in *MessageWithBody, opts ...grpc.CallOption) (*empty.Empty, error)
	PostWithEmptyBody(ctx context.Context, in *Body, opts ...grpc.CallOption) (*empty.Empty, error)
	CheckGetQueryParams(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	CheckNestedEnumGetQueryParams(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	CheckPostQueryParams(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	OverwriteResponseContentType(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*wrappers.StringValue, error)
	CheckExternalPathEnum(ctx context.Context, in *pathenum.MessageWithPathEnum, opts ...grpc.CallOption) (*empty.Empty, error)
	CheckExternalNestedPathEnum(ctx context.Context, in *pathenum.MessageWithNestedPathEnum, opts ...grpc.CallOption) (*empty.Empty, error)
}

type aBitOfEverythingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewABitOfEverythingServiceClient(cc grpc.ClientConnInterface) ABitOfEverythingServiceClient {
	return &aBitOfEverythingServiceClient{cc}
}

func (c *aBitOfEverythingServiceClient) Create(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) CreateBody(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CreateBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Lookup(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Lookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Update(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) UpdateV2(ctx context.Context, in *UpdateV2Request, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/UpdateV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Delete(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) GetQuery(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/GetQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) GetRepeatedQuery(ctx context.Context, in *ABitOfEverythingRepeated, opts ...grpc.CallOption) (*ABitOfEverythingRepeated, error) {
	out := new(ABitOfEverythingRepeated)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/GetRepeatedQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Echo(ctx context.Context, in *sub.StringMessage, opts ...grpc.CallOption) (*sub.StringMessage, error) {
	out := new(sub.StringMessage)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) DeepPathEcho(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/DeepPathEcho", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) NoBindings(ctx context.Context, in *duration.Duration, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/NoBindings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Timeout(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Timeout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) ErrorWithDetails(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/ErrorWithDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) GetMessageWithBody(ctx context.Context, in *MessageWithBody, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/GetMessageWithBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) PostWithEmptyBody(ctx context.Context, in *Body, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/PostWithEmptyBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) CheckGetQueryParams(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckGetQueryParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) CheckNestedEnumGetQueryParams(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckNestedEnumGetQueryParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) CheckPostQueryParams(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckPostQueryParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) OverwriteResponseContentType(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*wrappers.StringValue, error) {
	out := new(wrappers.StringValue)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/OverwriteResponseContentType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) CheckExternalPathEnum(ctx context.Context, in *pathenum.MessageWithPathEnum, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckExternalPathEnum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) CheckExternalNestedPathEnum(ctx context.Context, in *pathenum.MessageWithNestedPathEnum, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckExternalNestedPathEnum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ABitOfEverythingServiceServer is the server API for ABitOfEverythingService service.
type ABitOfEverythingServiceServer interface {
	// Create a new ABitOfEverything
	//
	// This API creates a new ABitOfEverything
	Create(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	CreateBody(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	Lookup(context.Context, *sub2.IdMessage) (*ABitOfEverything, error)
	Update(context.Context, *ABitOfEverything) (*empty.Empty, error)
	UpdateV2(context.Context, *UpdateV2Request) (*empty.Empty, error)
	Delete(context.Context, *sub2.IdMessage) (*empty.Empty, error)
	GetQuery(context.Context, *ABitOfEverything) (*empty.Empty, error)
	GetRepeatedQuery(context.Context, *ABitOfEverythingRepeated) (*ABitOfEverythingRepeated, error)
	// Echo allows posting a StringMessage value.
	//
	// It also exposes multiple bindings.
	//
	// This makes it useful when validating that the OpenAPI v2 API
	// description exposes documentation correctly on all paths
	// defined as additional_bindings in the proto.
	Echo(context.Context, *sub.StringMessage) (*sub.StringMessage, error)
	DeepPathEcho(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	NoBindings(context.Context, *duration.Duration) (*empty.Empty, error)
	Timeout(context.Context, *empty.Empty) (*empty.Empty, error)
	ErrorWithDetails(context.Context, *empty.Empty) (*empty.Empty, error)
	GetMessageWithBody(context.Context, *MessageWithBody) (*empty.Empty, error)
	PostWithEmptyBody(context.Context, *Body) (*empty.Empty, error)
	CheckGetQueryParams(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	CheckNestedEnumGetQueryParams(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	CheckPostQueryParams(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	OverwriteResponseContentType(context.Context, *empty.Empty) (*wrappers.StringValue, error)
	CheckExternalPathEnum(context.Context, *pathenum.MessageWithPathEnum) (*empty.Empty, error)
	CheckExternalNestedPathEnum(context.Context, *pathenum.MessageWithNestedPathEnum) (*empty.Empty, error)
}

// UnimplementedABitOfEverythingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedABitOfEverythingServiceServer struct {
}

func (*UnimplementedABitOfEverythingServiceServer) Create(ctx context.Context, req *ABitOfEverything) (*ABitOfEverything, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) CreateBody(ctx context.Context, req *ABitOfEverything) (*ABitOfEverything, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBody not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) Lookup(ctx context.Context, req *sub2.IdMessage) (*ABitOfEverything, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) Update(ctx context.Context, req *ABitOfEverything) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) UpdateV2(ctx context.Context, req *UpdateV2Request) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateV2 not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) Delete(ctx context.Context, req *sub2.IdMessage) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) GetQuery(ctx context.Context, req *ABitOfEverything) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuery not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) GetRepeatedQuery(ctx context.Context, req *ABitOfEverythingRepeated) (*ABitOfEverythingRepeated, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepeatedQuery not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) Echo(ctx context.Context, req *sub.StringMessage) (*sub.StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) DeepPathEcho(ctx context.Context, req *ABitOfEverything) (*ABitOfEverything, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeepPathEcho not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) NoBindings(ctx context.Context, req *duration.Duration) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoBindings not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) Timeout(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Timeout not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) ErrorWithDetails(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ErrorWithDetails not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) GetMessageWithBody(ctx context.Context, req *MessageWithBody) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageWithBody not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) PostWithEmptyBody(ctx context.Context, req *Body) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostWithEmptyBody not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) CheckGetQueryParams(ctx context.Context, req *ABitOfEverything) (*ABitOfEverything, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckGetQueryParams not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) CheckNestedEnumGetQueryParams(ctx context.Context, req *ABitOfEverything) (*ABitOfEverything, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNestedEnumGetQueryParams not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) CheckPostQueryParams(ctx context.Context, req *ABitOfEverything) (*ABitOfEverything, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPostQueryParams not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) OverwriteResponseContentType(ctx context.Context, req *empty.Empty) (*wrappers.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OverwriteResponseContentType not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) CheckExternalPathEnum(ctx context.Context, req *pathenum.MessageWithPathEnum) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckExternalPathEnum not implemented")
}
func (*UnimplementedABitOfEverythingServiceServer) CheckExternalNestedPathEnum(ctx context.Context, req *pathenum.MessageWithNestedPathEnum) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckExternalNestedPathEnum not implemented")
}

func RegisterABitOfEverythingServiceServer(s *grpc.Server, srv ABitOfEverythingServiceServer) {
	s.RegisterService(&_ABitOfEverythingService_serviceDesc, srv)
}

func _ABitOfEverythingService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Create(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_CreateBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).CreateBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CreateBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).CreateBody(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sub2.IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Lookup(ctx, req.(*sub2.IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Update(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_UpdateV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).UpdateV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/UpdateV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).UpdateV2(ctx, req.(*UpdateV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sub2.IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Delete(ctx, req.(*sub2.IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_GetQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).GetQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/GetQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).GetQuery(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_GetRepeatedQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverythingRepeated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).GetRepeatedQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/GetRepeatedQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).GetRepeatedQuery(ctx, req.(*ABitOfEverythingRepeated))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sub.StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Echo(ctx, req.(*sub.StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_DeepPathEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).DeepPathEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/DeepPathEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).DeepPathEcho(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_NoBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(duration.Duration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).NoBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/NoBindings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).NoBindings(ctx, req.(*duration.Duration))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Timeout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Timeout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/Timeout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Timeout(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_ErrorWithDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).ErrorWithDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/ErrorWithDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).ErrorWithDetails(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_GetMessageWithBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageWithBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).GetMessageWithBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/GetMessageWithBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).GetMessageWithBody(ctx, req.(*MessageWithBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_PostWithEmptyBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Body)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).PostWithEmptyBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/PostWithEmptyBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).PostWithEmptyBody(ctx, req.(*Body))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_CheckGetQueryParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).CheckGetQueryParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckGetQueryParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).CheckGetQueryParams(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_CheckNestedEnumGetQueryParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).CheckNestedEnumGetQueryParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckNestedEnumGetQueryParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).CheckNestedEnumGetQueryParams(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_CheckPostQueryParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).CheckPostQueryParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckPostQueryParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).CheckPostQueryParams(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_OverwriteResponseContentType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).OverwriteResponseContentType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/OverwriteResponseContentType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).OverwriteResponseContentType(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_CheckExternalPathEnum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pathenum.MessageWithPathEnum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).CheckExternalPathEnum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckExternalPathEnum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).CheckExternalPathEnum(ctx, req.(*pathenum.MessageWithPathEnum))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_CheckExternalNestedPathEnum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pathenum.MessageWithNestedPathEnum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).CheckExternalNestedPathEnum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.ABitOfEverythingService/CheckExternalNestedPathEnum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).CheckExternalNestedPathEnum(ctx, req.(*pathenum.MessageWithNestedPathEnum))
	}
	return interceptor(ctx, in, info, handler)
}

var _ABitOfEverythingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.internal.examplepb.ABitOfEverythingService",
	HandlerType: (*ABitOfEverythingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ABitOfEverythingService_Create_Handler,
		},
		{
			MethodName: "CreateBody",
			Handler:    _ABitOfEverythingService_CreateBody_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _ABitOfEverythingService_Lookup_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ABitOfEverythingService_Update_Handler,
		},
		{
			MethodName: "UpdateV2",
			Handler:    _ABitOfEverythingService_UpdateV2_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ABitOfEverythingService_Delete_Handler,
		},
		{
			MethodName: "GetQuery",
			Handler:    _ABitOfEverythingService_GetQuery_Handler,
		},
		{
			MethodName: "GetRepeatedQuery",
			Handler:    _ABitOfEverythingService_GetRepeatedQuery_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _ABitOfEverythingService_Echo_Handler,
		},
		{
			MethodName: "DeepPathEcho",
			Handler:    _ABitOfEverythingService_DeepPathEcho_Handler,
		},
		{
			MethodName: "NoBindings",
			Handler:    _ABitOfEverythingService_NoBindings_Handler,
		},
		{
			MethodName: "Timeout",
			Handler:    _ABitOfEverythingService_Timeout_Handler,
		},
		{
			MethodName: "ErrorWithDetails",
			Handler:    _ABitOfEverythingService_ErrorWithDetails_Handler,
		},
		{
			MethodName: "GetMessageWithBody",
			Handler:    _ABitOfEverythingService_GetMessageWithBody_Handler,
		},
		{
			MethodName: "PostWithEmptyBody",
			Handler:    _ABitOfEverythingService_PostWithEmptyBody_Handler,
		},
		{
			MethodName: "CheckGetQueryParams",
			Handler:    _ABitOfEverythingService_CheckGetQueryParams_Handler,
		},
		{
			MethodName: "CheckNestedEnumGetQueryParams",
			Handler:    _ABitOfEverythingService_CheckNestedEnumGetQueryParams_Handler,
		},
		{
			MethodName: "CheckPostQueryParams",
			Handler:    _ABitOfEverythingService_CheckPostQueryParams_Handler,
		},
		{
			MethodName: "OverwriteResponseContentType",
			Handler:    _ABitOfEverythingService_OverwriteResponseContentType_Handler,
		},
		{
			MethodName: "CheckExternalPathEnum",
			Handler:    _ABitOfEverythingService_CheckExternalPathEnum_Handler,
		},
		{
			MethodName: "CheckExternalNestedPathEnum",
			Handler:    _ABitOfEverythingService_CheckExternalNestedPathEnum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/internal/proto/examplepb/a_bit_of_everything.proto",
}

// CamelCaseServiceNameClient is the client API for CamelCaseServiceName service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CamelCaseServiceNameClient interface {
	Empty(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type camelCaseServiceNameClient struct {
	cc grpc.ClientConnInterface
}

func NewCamelCaseServiceNameClient(cc grpc.ClientConnInterface) CamelCaseServiceNameClient {
	return &camelCaseServiceNameClient{cc}
}

func (c *camelCaseServiceNameClient) Empty(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.camelCaseServiceName/Empty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CamelCaseServiceNameServer is the server API for CamelCaseServiceName service.
type CamelCaseServiceNameServer interface {
	Empty(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedCamelCaseServiceNameServer can be embedded to have forward compatible implementations.
type UnimplementedCamelCaseServiceNameServer struct {
}

func (*UnimplementedCamelCaseServiceNameServer) Empty(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Empty not implemented")
}

func RegisterCamelCaseServiceNameServer(s *grpc.Server, srv CamelCaseServiceNameServer) {
	s.RegisterService(&_CamelCaseServiceName_serviceDesc, srv)
}

func _CamelCaseServiceName_Empty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CamelCaseServiceNameServer).Empty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.camelCaseServiceName/Empty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CamelCaseServiceNameServer).Empty(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CamelCaseServiceName_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.internal.examplepb.camelCaseServiceName",
	HandlerType: (*CamelCaseServiceNameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Empty",
			Handler:    _CamelCaseServiceName_Empty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/internal/proto/examplepb/a_bit_of_everything.proto",
}

// AnotherServiceWithNoBindingsClient is the client API for AnotherServiceWithNoBindings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnotherServiceWithNoBindingsClient interface {
	NoBindings(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type anotherServiceWithNoBindingsClient struct {
	cc grpc.ClientConnInterface
}

func NewAnotherServiceWithNoBindingsClient(cc grpc.ClientConnInterface) AnotherServiceWithNoBindingsClient {
	return &anotherServiceWithNoBindingsClient{cc}
}

func (c *anotherServiceWithNoBindingsClient) NoBindings(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.internal.examplepb.AnotherServiceWithNoBindings/NoBindings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnotherServiceWithNoBindingsServer is the server API for AnotherServiceWithNoBindings service.
type AnotherServiceWithNoBindingsServer interface {
	NoBindings(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedAnotherServiceWithNoBindingsServer can be embedded to have forward compatible implementations.
type UnimplementedAnotherServiceWithNoBindingsServer struct {
}

func (*UnimplementedAnotherServiceWithNoBindingsServer) NoBindings(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoBindings not implemented")
}

func RegisterAnotherServiceWithNoBindingsServer(s *grpc.Server, srv AnotherServiceWithNoBindingsServer) {
	s.RegisterService(&_AnotherServiceWithNoBindings_serviceDesc, srv)
}

func _AnotherServiceWithNoBindings_NoBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnotherServiceWithNoBindingsServer).NoBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.internal.examplepb.AnotherServiceWithNoBindings/NoBindings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnotherServiceWithNoBindingsServer).NoBindings(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnotherServiceWithNoBindings_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.internal.examplepb.AnotherServiceWithNoBindings",
	HandlerType: (*AnotherServiceWithNoBindingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NoBindings",
			Handler:    _AnotherServiceWithNoBindings_NoBindings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/internal/proto/examplepb/a_bit_of_everything.proto",
}
