// Code generated by go-swagger; DO NOT EDIT.

package a_bit_of_everything

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewABitOfEverythingServiceOverwriteResponseContentTypeParams creates a new ABitOfEverythingServiceOverwriteResponseContentTypeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewABitOfEverythingServiceOverwriteResponseContentTypeParams() *ABitOfEverythingServiceOverwriteResponseContentTypeParams {
	return &ABitOfEverythingServiceOverwriteResponseContentTypeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewABitOfEverythingServiceOverwriteResponseContentTypeParamsWithTimeout creates a new ABitOfEverythingServiceOverwriteResponseContentTypeParams object
// with the ability to set a timeout on a request.
func NewABitOfEverythingServiceOverwriteResponseContentTypeParamsWithTimeout(timeout time.Duration) *ABitOfEverythingServiceOverwriteResponseContentTypeParams {
	return &ABitOfEverythingServiceOverwriteResponseContentTypeParams{
		timeout: timeout,
	}
}

// NewABitOfEverythingServiceOverwriteResponseContentTypeParamsWithContext creates a new ABitOfEverythingServiceOverwriteResponseContentTypeParams object
// with the ability to set a context for a request.
func NewABitOfEverythingServiceOverwriteResponseContentTypeParamsWithContext(ctx context.Context) *ABitOfEverythingServiceOverwriteResponseContentTypeParams {
	return &ABitOfEverythingServiceOverwriteResponseContentTypeParams{
		Context: ctx,
	}
}

// NewABitOfEverythingServiceOverwriteResponseContentTypeParamsWithHTTPClient creates a new ABitOfEverythingServiceOverwriteResponseContentTypeParams object
// with the ability to set a custom HTTPClient for a request.
func NewABitOfEverythingServiceOverwriteResponseContentTypeParamsWithHTTPClient(client *http.Client) *ABitOfEverythingServiceOverwriteResponseContentTypeParams {
	return &ABitOfEverythingServiceOverwriteResponseContentTypeParams{
		HTTPClient: client,
	}
}

/*
ABitOfEverythingServiceOverwriteResponseContentTypeParams contains all the parameters to send to the API endpoint

	for the a bit of everything service overwrite response content type operation.

	Typically these are written to a http.Request.
*/
type ABitOfEverythingServiceOverwriteResponseContentTypeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the a bit of everything service overwrite response content type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ABitOfEverythingServiceOverwriteResponseContentTypeParams) WithDefaults() *ABitOfEverythingServiceOverwriteResponseContentTypeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the a bit of everything service overwrite response content type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ABitOfEverythingServiceOverwriteResponseContentTypeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the a bit of everything service overwrite response content type params
func (o *ABitOfEverythingServiceOverwriteResponseContentTypeParams) WithTimeout(timeout time.Duration) *ABitOfEverythingServiceOverwriteResponseContentTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the a bit of everything service overwrite response content type params
func (o *ABitOfEverythingServiceOverwriteResponseContentTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the a bit of everything service overwrite response content type params
func (o *ABitOfEverythingServiceOverwriteResponseContentTypeParams) WithContext(ctx context.Context) *ABitOfEverythingServiceOverwriteResponseContentTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the a bit of everything service overwrite response content type params
func (o *ABitOfEverythingServiceOverwriteResponseContentTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the a bit of everything service overwrite response content type params
func (o *ABitOfEverythingServiceOverwriteResponseContentTypeParams) WithHTTPClient(client *http.Client) *ABitOfEverythingServiceOverwriteResponseContentTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the a bit of everything service overwrite response content type params
func (o *ABitOfEverythingServiceOverwriteResponseContentTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ABitOfEverythingServiceOverwriteResponseContentTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
