/*
 * A Bit of Everything
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package abe
// ExamplepbSnakeCaseEnum : - value_c: buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE  - value_d: buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
type ExamplepbSnakeCaseEnum string

// List of examplepbSnake_case_enum
const (
	C_ExamplepbSnakeCaseEnum ExamplepbSnakeCaseEnum = "value_c"
	D_ExamplepbSnakeCaseEnum ExamplepbSnakeCaseEnum = "value_d"
)
