source 'https://rubygems.org'

group :development, :test do
  gem 'github-pages', '~> 207'
  gem 'jekyll', '~> 3.9.0'
  gem 'jekyll-redirect-from', '~> 0.15.0'
  gem 'jekyll-sitemap', '~> 1.4.0'
  gem 'jekyll-toc', '~> 0.5.1'
end
