on:
  push:
    paths:
      - .devcontainer/devcontainer.json
      - .github/workflows/devcontainer.yml
      - .github/Dockerfile
permissions:
  contents: read
  packages: write
name: devcontainer
jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Rebuild dev container image
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3
        with:
          imageName: ghcr.io/grpc-ecosystem/grpc-gateway/build-env
          cacheFrom: ghcr.io/grpc-ecosystem/grpc-gateway/build-env
          push: filter
          refFilterForPush: refs/heads/main
