on:
  push:
    branches:
      - main
    paths:
      - protoc-gen-openapiv2/options/*.proto
permissions:
  contents: read
name: main
jobs:
  proto_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3
        with:
          check-latest: true
      - run: make install
      # Limit pushes to protoc-gen-openapiv2 files. This is a total hack.
      # It excludes all the files that we don't want to publish, just for the push step.
      - run: echo -e "    - examples\n    - internal\n    - runtime" >> buf.yaml
      - run: buf push --tag "${{ github.sha }}"
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
          PATH: $PATH:~/go/bin
